//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Net4Courier.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountSetup
    {
        public int ID { get; set; }
        public string PageName { get; set; }
        public string TransType { get; set; }
        public Nullable<int> DebitAccountId { get; set; }
        public Nullable<int> CreditAccountId { get; set; }
        public string SalesType { get; set; }
        public string ParcelType { get; set; }
    }
}
