//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Net4Courier.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AcFinancialYear
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AcFinancialYear()
        {
            this.PurchaseInvoices = new HashSet<PurchaseInvoice>();
            this.SalesInvoices = new HashSet<SalesInvoice>();
            this.tblSupplierAdjustments = new HashSet<tblSupplierAdjustment>();
            this.AcOPInvoiceMasters = new HashSet<AcOPInvoiceMaster>();
            this.AcOpeningMasters = new HashSet<AcOpeningMaster>();
        }
    
        public int AcFinancialYearID { get; set; }
        public Nullable<int> AcCompanyID { get; set; }
        public Nullable<System.DateTime> AcFYearFrom { get; set; }
        public Nullable<System.DateTime> AcFYearTo { get; set; }
        public string ReferenceName { get; set; }
        public Nullable<bool> StatusClose { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> BranchID { get; set; }
        public bool CurrentFinancialYear { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PurchaseInvoice> PurchaseInvoices { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SalesInvoice> SalesInvoices { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblSupplierAdjustment> tblSupplierAdjustments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AcOPInvoiceMaster> AcOPInvoiceMasters { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AcOpeningMaster> AcOpeningMasters { get; set; }
    }
}
