//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Net4Courier.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AcHeadAssign
    {
        public int ID { get; set; }
        public Nullable<int> CustomerAcHeadID { get; set; }
        public Nullable<int> CashAcHeadID { get; set; }
        public Nullable<int> SalesAcHeadID { get; set; }
        public Nullable<int> SupplierAcHeadID { get; set; }
        public Nullable<int> InventoryAcHeadID { get; set; }
        public Nullable<int> UnEarnedRevenueID { get; set; }
        public Nullable<int> DiscountAcHeadID { get; set; }
        public Nullable<int> Accompanyid { get; set; }
        public Nullable<int> AgentControlAccountID { get; set; }
        public Nullable<int> AgentCollectionChargesID { get; set; }
        public Nullable<int> AgentDeliveryChargesID { get; set; }
        public Nullable<int> AgentCollectionDepositID { get; set; }
        public Nullable<int> CustomerControlAcHeadID { get; set; }
        public Nullable<int> BranchID { get; set; }
        public Nullable<int> CODControlID { get; set; }
        public Nullable<int> FOCControlID { get; set; }
        public Nullable<int> UnPostedSalesAcHeadID { get; set; }
        public Nullable<int> MaterialCostControlReceivableAcHeadID { get; set; }
        public Nullable<int> ProvisionCostControlAcID { get; set; }
        public Nullable<int> OpenJobRevenueAcID { get; set; }
        public Nullable<int> AccruedCostControlAcID { get; set; }
    }
}
