//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Net4Courier.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AcOPInvoiceMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AcOPInvoiceMaster()
        {
            this.AcOPInvoiceDetails = new HashSet<AcOPInvoiceDetail>();
        }
    
        public int AcOPInvoiceMasterID { get; set; }
        public Nullable<int> AcHeadID { get; set; }
        public Nullable<int> AcFinancialYearID { get; set; }
        public Nullable<System.DateTime> OPDate { get; set; }
        public string Remarks { get; set; }
        public string StatusSDSC { get; set; }
        public Nullable<int> PartyID { get; set; }
        public Nullable<int> BranchID { get; set; }
        public string StatusSC { get; set; }
        public Nullable<int> AcJournalID { get; set; }
        public Nullable<int> SupplierTypeID { get; set; }
    
        public virtual AcFinancialYear AcFinancialYear { get; set; }
        public virtual AcHead AcHead { get; set; }
        public virtual BranchMaster BranchMaster { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AcOPInvoiceDetail> AcOPInvoiceDetails { get; set; }
    }
}
