//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Net4Courier.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class APIDetail
    {
        public int ID { get; set; }
        public string AppPage { get; set; }
        public string APIType { get; set; }
        public string APILink { get; set; }
        public string APIKeyname { get; set; }
        public string APIKeyValue { get; set; }
        public string APISignature { get; set; }
        public string APISignatureValue { get; set; }
    }
}
