//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Net4Courier.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AWBBOOKIssue
    {
        public int AWBBOOKIssueID { get; set; }
        public Nullable<System.DateTime> TransDate { get; set; }
        public Nullable<int> NoOfAWBs { get; set; }
        public string BookNo { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public string Documentno { get; set; }
        public Nullable<int> AcCompanyID { get; set; }
        public string AWBNOFrom { get; set; }
        public string AWBNOTo { get; set; }
        public int BranchID { get; set; }
        public Nullable<int> CreatedUserID { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedUserID { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    }
}
