//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Net4Courier.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CMS_BulkInscanMobile
    {
        public int ID { get; set; }
        public string BatchNo { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public Nullable<int> CourierID { get; set; }
        public Nullable<int> VehicleID { get; set; }
        public Nullable<System.DateTime> EntryDateTime { get; set; }
        public Nullable<int> EmpID { get; set; }
        public Nullable<int> TotalAWB { get; set; }
        public Nullable<int> FYearID { get; set; }
        public Nullable<int> AWBBatchID { get; set; }
        public Nullable<System.DateTime> ReceivedDate { get; set; }
        public Nullable<int> ReceivedBy { get; set; }
    }
}
