//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Net4Courier.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CMS_BulkInscanMobileDetail
    {
        public int DetailID { get; set; }
        public Nullable<int> BatchID { get; set; }
        public string AWBNo { get; set; }
        public Nullable<int> InScanID { get; set; }
    }
}
