//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Net4Courier.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ColoaderCostDetail
    {
        public int ColoaderCostDetailID { get; set; }
        public Nullable<int> CustomerInvoiceID { get; set; }
        public Nullable<int> CostTypeID { get; set; }
        public Nullable<int> CostDRHeadID { get; set; }
        public Nullable<int> CostCRHeadID { get; set; }
        public Nullable<int> RevenueHeadID { get; set; }
        public Nullable<decimal> Cost { get; set; }
        public Nullable<decimal> Revenue { get; set; }
        public string InvoiceHead { get; set; }
    }
}
