// Decompiled with JetBrains decompiler
// Type: Net4Courier.Models.ComapanyVM
// Assembly: Courier_27_09_16, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
// MVID: 2B3B4E05-393A-455A-A5DE-86374CE9B081
// Assembly location: D:\Courier09022018\Decompiled\obj\Release\Package\PackageTmp\bin\Net4Courier.dll

using System.ComponentModel.DataAnnotations;
using System.Web;

namespace Net4Courier.Models
{
  public class ComapanyVM
  {
    public int AcCompanyID { get; set; }

    public string AcCompany { get; set; }

    public int ParentID { get; set; }

    public int CountryID { get; set; }

    public int CityID { get; set; }

    public int StateID { get; set; }

    public int LocationID { get; set; }

    public int CurrencyID { get; set; }

    public string Address1 { get; set; }

    public string Address2 { get; set; }

    public string Address3 { get; set; }

    public string Phone { get; set; }

    public string EMail { get; set; }

    public int UserID { get; set; }

    public string KeyPerson { get; set; }

    public int DesignationID { get; set; }

    public string PhoneNo1 { get; set; }

    public string PhoneNo2 { get; set; }

    public string PhoneNo3 { get; set; }

    public string PhoneNo4 { get; set; }

    public string Mobile1 { get; set; }

    public string Mobile2 { get; set; }

    public string website { get; set; }

    public string CompanyPrefix { get; set; }

    public bool IsAWBAutoGenerated { get; set; }
    public bool AWBAlphaNumeric { get; set; }
    public string AWBFormat { get; set; }

    public string CountryName { get; set; }

    public string State { get; set; }

    public string CityName { get; set; }
     public string LocationName { get; set; }

    public string Currency { get; set; }
        public string InvoicePrefix { get; set; }
        public string InvoiceFormat { get; set; }
     public string LogoFileName { get; set; }
        public string LogoFilPath { get; set; }
        public int BranchCount { get; set; }
        public string BranchLocationName { get; set; }
        public bool Accept { get; set; }
        public bool AcceptNo { get; set; }
    }
    
    public class ImgViewModel
    {
        #region Properties  

        /// <summary>  
        /// Gets or sets Image file.  
        /// </summary>  
        [Required]
        [Display(Name = "Upload File")]
        public HttpPostedFileBase FileAttach { get; set; }

        public string FileName { get; set; }
         public ImgObj ImgLst { get; set; }
        
         public byte[] Image { get; set; }
        /// <summary>  
        /// Gets or sets Image file list.  
        /// </summary>  
        // public List<ImgObj> ImgLst { get; set; }

        #endregion
    }
    public class ImgObj
    {
        #region Properties  

        /// <summary>  
        /// Gets or sets Image ID.  
        /// </summary>  
        public int FileId { get; set; }

        /// <summary>  
        /// Gets or sets Image name.  
        /// </summary>  
        public string FileName { get; set; }

        /// <summary>  
        /// Gets or sets Image extension.  
        /// </summary>  
        public string FileContentType { get; set; }

        public string FileFullPath { get; set; }
        #endregion
    }
}
