//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Net4Courier.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConsignorMaster
    {
        public int ConsignorId { get; set; }
        public string ConsignorName { get; set; }
        public string ConsignorAddress1 { get; set; }
        public string ConsignorAddress2 { get; set; }
        public string ConsignorAddress3 { get; set; }
        public string ConsignorCountryname { get; set; }
        public string ConsignorCityName { get; set; }
        public string ConsignorLocationName { get; set; }
        public string ConsignorPhoneNo { get; set; }
        public string ConsignorContactName { get; set; }
        public string MobileNo { get; set; }
    }
}
