//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Net4Courier.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CourierDescription
    {
        public int CourierDescriptionID { get; set; }
        public string CourierDescription1 { get; set; }
        public Nullable<int> DepartmentID { get; set; }
        public bool StatusDefault { get; set; }
        public Nullable<double> Weight { get; set; }
    }
}
