//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Net4Courier.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CourierCollection
    {
        public int CollectionID { get; set; }
        public Nullable<System.DateTime> CollectedDate { get; set; }
        public Nullable<decimal> PickupCash { get; set; }
        public Nullable<decimal> MaterialCost { get; set; }
        public Nullable<decimal> OtherAmount { get; set; }
        public Nullable<int> CourierId { get; set; }
        public Nullable<bool> codpending { get; set; }
        public Nullable<bool> pickupcashpending { get; set; }
        public Nullable<decimal> COD { get; set; }
        public string AWBNumber { get; set; }
        public string Remarks { get; set; }
        public string CollectionType { get; set; }
        public Nullable<int> DRSRecpayID { get; set; }
        public Nullable<int> PaymentModeId { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public bool ChangeCOD { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    }
}
