//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Net4Courier.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CourierExpens
    {
        public int ExpenseID { get; set; }
        public System.DateTime ExpenseDate { get; set; }
        public Nullable<int> RevenueTypeID { get; set; }
        public Nullable<decimal> ExpenseAmount { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> DRSID { get; set; }
        public string ReferenceNo { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> BranchID { get; set; }
        public Nullable<int> FYearID { get; set; }
        public bool IsLocked { get; set; }
        public Nullable<int> DRSRecpayID { get; set; }
    }
}
