//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Net4Courier.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerNotification
    {
        public int NotificationId { get; set; }
        public int InScanId { get; set; }
        public int CustomerId { get; set; }
        public bool NotifyByEmail { get; set; }
        public bool NotifyBySMS { get; set; }
        public bool NotifyByWhatsApp { get; set; }
        public string MessageText { get; set; }
        public System.DateTime EntryDate { get; set; }
        public int UserId { get; set; }
        public Nullable<int> RecPayID { get; set; }
        public Nullable<int> PageTypeId { get; set; }
    }
}
