//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Net4Courier.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerRateAssign
    {
        public int CustomerRateAssignID { get; set; }
        public Nullable<int> CustomerRateTypeID { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<System.DateTime> EffectiveDate { get; set; }
    
        public virtual CustomerMaster CustomerMaster { get; set; }
        public virtual CustomerRateType CustomerRateType { get; set; }
    }
}
