//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Net4Courier.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CustomerMaster()
        {
            this.CustomerEnquiries = new HashSet<CustomerEnquiry>();
            this.CustomerRateAssigns = new HashSet<CustomerRateAssign>();
            this.SalesInvoices = new HashSet<SalesInvoice>();
            this.tblCustomerAdjustments = new HashSet<tblCustomerAdjustment>();
        }
    
        public int CustomerID { get; set; }
        public Nullable<int> AcCompanyID { get; set; }
        public string CustomerCode { get; set; }
        public string CustomerName { get; set; }
        public string CustomerType { get; set; }
        public Nullable<int> CustomerRateTypeID { get; set; }
        public string ReferenceCode { get; set; }
        public string ContactPerson { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string Address3 { get; set; }
        public string Phone { get; set; }
        public string Mobile { get; set; }
        public string Fax { get; set; }
        public string Email { get; set; }
        public string WebSite { get; set; }
        public Nullable<int> CountryID { get; set; }
        public Nullable<int> CityID { get; set; }
        public Nullable<int> LocationID { get; set; }
        public Nullable<int> CurrencyID { get; set; }
        public Nullable<bool> StatusActive { get; set; }
        public Nullable<decimal> CreditLimit { get; set; }
        public Nullable<bool> StatusTaxable { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public Nullable<bool> statusCommission { get; set; }
        public Nullable<bool> StatusGPA { get; set; }
        public Nullable<bool> StatusWalkIn { get; set; }
        public Nullable<int> CustomerRateTypeIntID { get; set; }
        public Nullable<int> CourierServiceID { get; set; }
        public Nullable<int> BranchID { get; set; }
        public string CustomerUsername { get; set; }
        public string Password { get; set; }
        public string VATTRN { get; set; }
        public Nullable<System.TimeSpan> OfficeOpenTime { get; set; }
        public Nullable<System.TimeSpan> OfficeCloseTime { get; set; }
        public string Referal { get; set; }
        public Nullable<int> BusinessTypeId { get; set; }
        public string CountryName { get; set; }
        public string LocationName { get; set; }
        public string CityName { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> DepotID { get; set; }
        public Nullable<int> ApprovedBy { get; set; }
        public Nullable<System.DateTime> ApprovedOn { get; set; }
        public string PlaceID { get; set; }
        public string CountryCode { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> OldCustomerId { get; set; }
        public bool APIEnabled { get; set; }
        public string GETAPILink { get; set; }
        public string POSTAPILink { get; set; }
    
        public virtual BranchMaster BranchMaster { get; set; }
        public virtual CityMaster CityMaster { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomerEnquiry> CustomerEnquiries { get; set; }
        public virtual LocationMaster LocationMaster { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomerRateAssign> CustomerRateAssigns { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SalesInvoice> SalesInvoices { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblCustomerAdjustment> tblCustomerAdjustments { get; set; }
    }
}
