//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Net4Courier.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerInvoiceDetail
    {
        public int CustomerInvoiceDetailID { get; set; }
        public Nullable<int> CustomerInvoiceID { get; set; }
        public string AWBNo { get; set; }
        public Nullable<decimal> CourierCharge { get; set; }
        public Nullable<int> InscanID { get; set; }
        public Nullable<decimal> TaxPercentage { get; set; }
        public Nullable<decimal> OtherCharge { get; set; }
        public Nullable<decimal> FuelSurcharge { get; set; }
        public Nullable<decimal> CustomCharge { get; set; }
        public Nullable<decimal> NetValue { get; set; }
        public Nullable<decimal> VATAmount { get; set; }
        public Nullable<decimal> SurchargePercent { get; set; }
    }
}
