//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Net4Courier.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerContract
    {
        public int CustomerContractID { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public Nullable<double> MaxWtInAWB { get; set; }
        public Nullable<double> TotWtInContract { get; set; }
        public Nullable<double> MaxAWBInPeriod { get; set; }
        public Nullable<System.DateTime> DateFrom { get; set; }
        public Nullable<System.DateTime> DateTo { get; set; }
    }
}
