//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Net4Courier.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Department
    {
        public int DepartmentID { get; set; }
        public string Department1 { get; set; }
        public Nullable<int> AcCompanyID { get; set; }
        public Nullable<int> UserID { get; set; }
        public bool StatusDefaultI { get; set; }
        public bool StatusDefaultD { get; set; }
        public Nullable<bool> StatusDefaultCargo { get; set; }
    }
}
