//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Net4Courier.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocumentNoSetup
    {
        public int ID { get; set; }
        public string DocumentName { get; set; }
        public string SystemPrefix { get; set; }
        public string Prefix { get; set; }
        public Nullable<int> StartNo { get; set; }
        public Nullable<int> BranchId { get; set; }
    }
}
