//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Net4Courier.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DomesticCODReceiptDetail
    {
        public int ReceiptDetailID { get; set; }
        public int ReceiptID { get; set; }
        public int InScanId { get; set; }
        public string AWBNo { get; set; }
        public decimal CourierCharge { get; set; }
        public Nullable<decimal> OtherCharge { get; set; }
        public decimal TotalCharge { get; set; }
        public decimal AmountAllocate { get; set; }
        public Nullable<decimal> Discount { get; set; }
    
        public virtual DomesticCODReceipt DomesticCODReceipt { get; set; }
        public virtual DomesticCODReceipt DomesticCODReceipt1 { get; set; }
    }
}
