//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Net4Courier.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DRR
    {
        public int DRRID { get; set; }
        public Nullable<System.DateTime> DRRDate { get; set; }
        public Nullable<int> DRSID { get; set; }
        public Nullable<int> DRSRecPayID { get; set; }
        public Nullable<int> CourierId { get; set; }
        public decimal ReconciledAmount { get; set; }
        public Nullable<int> BranchID { get; set; }
        public Nullable<int> AcJournalID { get; set; }
        public string StatusDRR { get; set; }
        public string StatusRunSheet { get; set; }
        public int UserID { get; set; }
        public Nullable<int> FYearID { get; set; }
        public string DRRNo { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
    }
}
