//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Net4Courier.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DRRDetail
    {
        public int ID { get; set; }
        public Nullable<int> DRRID { get; set; }
        public string TransactionType { get; set; }
        public Nullable<int> ReferenceId { get; set; }
        public string Reference { get; set; }
        public Nullable<decimal> CODAmount { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public Nullable<decimal> MCReceived { get; set; }
        public Nullable<decimal> Receipt { get; set; }
        public Nullable<decimal> PKPCash { get; set; }
        public Nullable<decimal> Expense { get; set; }
        public Nullable<decimal> Total { get; set; }
        public Nullable<decimal> MCPaid { get; set; }
        public bool MCPaymentPrint { get; set; }
        public string confirmation { get; set; }
        public Nullable<int> InScanID { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public Nullable<int> InvoiceId { get; set; }
        public Nullable<int> RecPayID { get; set; }
        public Nullable<int> ACHeadID { get; set; }
        public Nullable<int> ShipmentDetailId { get; set; }
        public bool PODStatus { get; set; }
        public bool ChequeStatus { get; set; }
        public Nullable<decimal> ChequeAmount { get; set; }
        public Nullable<decimal> SettlementAmount { get; set; }
        public string ChequeNo { get; set; }
        public bool TaxInclude { get; set; }
        public Nullable<decimal> CODVat { get; set; }
    }
}
