//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Net4Courier.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DRSMultiple
    {
        public int ID { get; set; }
        public Nullable<int> PODID { get; set; }
        public Nullable<int> DRSID { get; set; }
        public Nullable<int> InScanID { get; set; }
        public Nullable<int> ShipmentDetailID { get; set; }
        public Nullable<int> TotalPiecs { get; set; }
        public Nullable<decimal> TotalWeight { get; set; }
        public Nullable<int> DeliveredPiecs { get; set; }
        public Nullable<decimal> DeliveredWeight { get; set; }
        public Nullable<int> EmpID { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
    }
}
