//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Net4Courier.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DRSRecPay
    {
        public int DRSRecPayID { get; set; }
        public System.DateTime DRSRecPayDate { get; set; }
        public string DocumentNo { get; set; }
        public int DRSID { get; set; }
        public string BankName { get; set; }
        public string ChequeNo { get; set; }
        public Nullable<System.DateTime> ChequeDate { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> AcJournalID { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<int> FYearID { get; set; }
        public Nullable<int> AcCompanyID { get; set; }
        public Nullable<decimal> EXRate { get; set; }
        public Nullable<decimal> ReceivedAmount { get; set; }
        public string Status { get; set; }
        public string StatusEntry { get; set; }
        public Nullable<int> DeliveredBy { get; set; }
        public Nullable<int> ReceivedBy { get; set; }
        public Nullable<int> BranchId { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> DRRID { get; set; }
        public Nullable<int> DRSBased { get; set; }
        public Nullable<decimal> CollectedAmount { get; set; }
        public Nullable<System.DateTime> DRSDate { get; set; }
        public Nullable<System.DateTime> PODDate { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
    }
}
