//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Net4Courier.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DRSRecPayDetail
    {
        public int DRSRecPayDetailID { get; set; }
        public int DRSRecPayID { get; set; }
        public string AWBNO { get; set; }
        public int InScanID { get; set; }
        public decimal CourierCharge { get; set; }
        public decimal MaterialCost { get; set; }
        public Nullable<decimal> CCReceived { get; set; }
        public Nullable<decimal> MCReceived { get; set; }
        public string Remarks { get; set; }
        public bool StatusClose { get; set; }
        public Nullable<decimal> Discount { get; set; }
    }
}
