//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Net4Courier.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmpZoneAllocationDetail
    {
        public int EmpZoneAllocationDetailID { get; set; }
        public int EmpZoneAllocationID { get; set; }
        public int ZoneChartDetailID { get; set; }
        public Nullable<bool> Statusupdate { get; set; }
        public Nullable<int> ZoneId { get; set; }
    }
}
