//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Net4Courier.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExpenseDetail
    {
        public int ExpenseDetailID { get; set; }
        public Nullable<int> ExpenseID { get; set; }
        public string ExpenseType { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public Nullable<int> ItemUnitID { get; set; }
        public Nullable<decimal> Rate { get; set; }
        public Nullable<int> DebitAcHeadID { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public Nullable<int> JobID { get; set; }
    
        public virtual AcHead AcHead { get; set; }
        public virtual Expense Expense { get; set; }
        public virtual ItemUnit ItemUnit { get; set; }
    }
}
