//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Net4Courier.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExportShipmentDetail
    {
        public int ShipmentDetailID { get; set; }
        public int ExportID { get; set; }
        public string MAWB { get; set; }
        public string AWBNo { get; set; }
        public int PCS { get; set; }
        public decimal Weight { get; set; }
        public string Contents { get; set; }
        public string Shipper { get; set; }
        public decimal Value { get; set; }
        public string Receiver { get; set; }
        public string DestinationCountry { get; set; }
        public string DestinationCity { get; set; }
        public string BagNo { get; set; }
        public int CurrencyID { get; set; }
        public int FwdAgentId { get; set; }
        public string FwdAgentAWBNo { get; set; }
        public Nullable<System.DateTime> FwdDate { get; set; }
        public string FwdFlight { get; set; }
        public Nullable<decimal> FwdCharge { get; set; }
        public Nullable<decimal> OtherCharge { get; set; }
        public Nullable<int> InscanId { get; set; }
        public Nullable<int> InboundShipmentID { get; set; }
        public Nullable<int> ImportShipmentDetailID { get; set; }
        public Nullable<decimal> VerifiedWeight { get; set; }
        public string OriginCity { get; set; }
        public string OriginCountry { get; set; }
        public Nullable<System.DateTime> AWBDate { get; set; }
        public string ExpBagNo { get; set; }
        public bool APITracking { get; set; }
    }
}
