//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Net4Courier.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FAInvoiceDetail
    {
        public int FAInvoiceDetailID { get; set; }
        public Nullable<int> FAInvoiceID { get; set; }
        public Nullable<int> InScanInternationalID { get; set; }
        public string FAAWBNO { get; set; }
        public Nullable<decimal> ForwardingCharge { get; set; }
        public Nullable<decimal> FInvoiceAmt { get; set; }
        public Nullable<decimal> FuelSurchargePer { get; set; }
        public Nullable<decimal> FuelSurcharge { get; set; }
        public Nullable<decimal> OriginalAmt { get; set; }
    
        public virtual FAInvoice FAInvoice { get; set; }
    }
}
