//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Net4Courier.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ForwardingAgentMaster
    {
        public int FAgentID { get; set; }
        public int AcCompanyID { get; set; }
        public string FAgentName { get; set; }
        public string ReferenceCode { get; set; }
        public string ContactPerson { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string Phone { get; set; }
        public string Fax { get; set; }
        public string Email { get; set; }
        public string WebSite { get; set; }
        public int CountryID { get; set; }
        public int CityID { get; set; }
        public int CurrencyID { get; set; }
        public Nullable<int> ZoneCategoryID { get; set; }
        public bool StatusSigned { get; set; }
        public bool StatusActive { get; set; }
        public string FAgentCode { get; set; }
        public Nullable<int> AcHeadID { get; set; }
        public Nullable<bool> StatusDefault { get; set; }
        public Nullable<int> StateID { get; set; }
        public Nullable<int> CourierServiceID { get; set; }
        public string CountryName { get; set; }
        public string CityName { get; set; }
        public string LocationName { get; set; }
        public string Address3 { get; set; }
        public int SupplierID { get; set; }
    }
}
