//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Net4Courier.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ForwardingAgentRate
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ForwardingAgentRate()
        {
            this.ForwardingAgentRateDets = new HashSet<ForwardingAgentRateDet>();
        }
    
        public int FAgentRateID { get; set; }
        public int FAgentID { get; set; }
        public int ZoneChartID { get; set; }
        public Nullable<int> CountryID { get; set; }
        public Nullable<int> CourierServiceID { get; set; }
        public decimal BaseWeight { get; set; }
        public decimal BaseRate { get; set; }
    
        public virtual CourierService CourierService { get; set; }
        public virtual ZoneChart ZoneChart { get; set; }
        public virtual ZoneChart ZoneChart1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ForwardingAgentRateDet> ForwardingAgentRateDets { get; set; }
    }
}
