//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Net4Courier.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FuelSurcharge
    {
        public int ID { get; set; }
        public int FAgentID { get; set; }
        public string Month { get; set; }
        public double CostRate { get; set; }
        public Nullable<double> SaleRate { get; set; }
    }
}
