//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Net4Courier.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GeneralSetup
    {
        public int SetupID { get; set; }
        public Nullable<int> AcCompanyId { get; set; }
        public Nullable<int> BranchId { get; set; }
        public Nullable<int> SetupTypeID { get; set; }
        public string SetupName { get; set; }
        public string Text1 { get; set; }
        public string Text2 { get; set; }
        public string Text3 { get; set; }
        public string Text4 { get; set; }
        public string Text5 { get; set; }
    }
}
