//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Net4Courier.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImpExp
    {
        public int ImpExpID { get; set; }
        public System.DateTime ImportDate { get; set; }
        public string FName { get; set; }
        public int Employee { get; set; }
        public string Status { get; set; }
    }
}
