//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Net4Courier.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImportShipmentDetail
    {
        public int ShipmentDetailID { get; set; }
        public int ImportID { get; set; }
        public string AWB { get; set; }
        public System.DateTime AWBDate { get; set; }
        public int PCS { get; set; }
        public decimal Weight { get; set; }
        public string Contents { get; set; }
        public string Shipper { get; set; }
        public decimal CustomValue { get; set; }
        public decimal COD { get; set; }
        public string Receiver { get; set; }
        public string ReceiverContact { get; set; }
        public string ReceiverAddress { get; set; }
        public string ReceiverTelephone { get; set; }
        public string DestinationCountry { get; set; }
        public string DestinationCity { get; set; }
        public string BagNo { get; set; }
        public int CurrencyID { get; set; }
        public Nullable<int> ExportShipmentID { get; set; }
        public Nullable<int> QuickInscanID { get; set; }
        public Nullable<int> StatusTypeId { get; set; }
        public Nullable<int> CourierStatusID { get; set; }
        public Nullable<int> DRSID { get; set; }
        public Nullable<int> CODReceiptId { get; set; }
        public string DestinationLocation { get; set; }
        public string ImportType { get; set; }
        public string Route { get; set; }
        public string MAWB { get; set; }
        public string GroupCode { get; set; }
        public Nullable<System.DateTime> FlightDate { get; set; }
        public string FlightNo { get; set; }
        public Nullable<int> ShipmentInvoiceId { get; set; }
        public Nullable<int> DRRID { get; set; }
        public Nullable<int> PODID { get; set; }
    }
}
