//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Net4Courier.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImportShipment
    {
        public int ID { get; set; }
        public string ManifestNumber { get; set; }
        public string OriginAirportCity { get; set; }
        public string DestinationAirportCity { get; set; }
        public Nullable<System.DateTime> FlightDate { get; set; }
        public string FlightNo { get; set; }
        public string MAWB { get; set; }
        public string CD { get; set; }
        public Nullable<int> Bags { get; set; }
        public string RunNo { get; set; }
        public string Type { get; set; }
        public int TotalAWB { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int AgentID { get; set; }
        public int AgentLoginID { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> ShipmentTypeId { get; set; }
        public Nullable<int> AcFinancialYearID { get; set; }
        public Nullable<decimal> Weight { get; set; }
        public Nullable<int> ParcelNo { get; set; }
        public string Route { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> EnteredDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public int BranchID { get; set; }
    }
}
