//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Net4Courier.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Import
    {
        public int ImportID { get; set; }
        public string AWBNo { get; set; }
        public System.DateTime InScanDate { get; set; }
        public Nullable<int> DepartmentID { get; set; }
        public Nullable<int> OriginID { get; set; }
        public string DestinationID { get; set; }
        public Nullable<int> CustomerRateTypeID { get; set; }
        public string Pieces { get; set; }
        public Nullable<double> StatedWeight { get; set; }
        public Nullable<int> CourierDescriptionID { get; set; }
        public Nullable<int> CourierServiceID { get; set; }
        public Nullable<int> CollectedBy { get; set; }
        public int ReceivedBy { get; set; }
        public decimal CourierCharge { get; set; }
        public Nullable<decimal> OtherCharge { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> CourierStatusID { get; set; }
        public string StatusPaymentMode { get; set; }
        public Nullable<bool> StatusClose { get; set; }
        public string StatusInScan { get; set; }
        public string StatusPickUp { get; set; }
        public int UserID { get; set; }
        public Nullable<int> MovementID { get; set; }
        public Nullable<bool> Statuspost { get; set; }
        public Nullable<int> ConsignorCityID { get; set; }
        public Nullable<int> ConsigneeCityID { get; set; }
        public Nullable<int> ExportNo { get; set; }
        public Nullable<int> AcCompanyID { get; set; }
        public Nullable<bool> StatusExport { get; set; }
        public Nullable<System.DateTime> ExportDate { get; set; }
        public Nullable<int> ImportNo { get; set; }
        public Nullable<System.DateTime> ImportDate { get; set; }
        public Nullable<System.DateTime> DeliveryDate { get; set; }
        public string ReceiverName { get; set; }
        public string Consignor { get; set; }
        public string Consignee { get; set; }
        public Nullable<int> TaxconfigurationID { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public string ConsigneeAddress { get; set; }
        public string ConsignorAddress { get; set; }
        public string ConsigneePhone { get; set; }
        public string ConsignorPhone { get; set; }
        public Nullable<int> ConsignorCountryID { get; set; }
        public Nullable<int> ConsigneeCountryID { get; set; }
        public Nullable<int> ConsignorLocationID { get; set; }
        public Nullable<int> ConsigneeLocationID { get; set; }
        public Nullable<System.DateTime> VerifiedDate { get; set; }
        public Nullable<int> InscanID { get; set; }
        public Nullable<int> IAgentID { get; set; }
        public string FlightNo { get; set; }
        public string MAWBNO { get; set; }
        public Nullable<int> TotPackage { get; set; }
        public Nullable<double> TotWeight { get; set; }
        public string TotPieces { get; set; }
        public Nullable<decimal> ClearingCharge { get; set; }
        public string BagNo { get; set; }
        public Nullable<decimal> FuelSurchargePer { get; set; }
        public Nullable<int> FagentID { get; set; }
        public string FAWBNO { get; set; }
        public string ContentItem { get; set; }
        public Nullable<decimal> Value { get; set; }
        public Nullable<bool> StatusInsert { get; set; }
    }
}
