//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Net4Courier.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InboundAWBBatch
    {
        public int ID { get; set; }
        public string BatchNumber { get; set; }
        public System.DateTime BatchDate { get; set; }
        public int BranchID { get; set; }
        public int AcFinancialYearid { get; set; }
        public Nullable<int> QuickInScanId { get; set; }
        public Nullable<int> DRSId { get; set; }
        public Nullable<int> PODID { get; set; }
        public Nullable<int> TotalAWB { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public int CustomerID { get; set; }
        public Nullable<int> CourierStatusID { get; set; }
        public string EntrySource { get; set; }
        public string OriginAirportCity { get; set; }
        public string DestinationAirportCity { get; set; }
        public Nullable<System.DateTime> FlightDate { get; set; }
        public string FlightNo { get; set; }
        public string MAWB { get; set; }
        public Nullable<int> Bags { get; set; }
        public string RunNo { get; set; }
        public Nullable<int> ParcelNo { get; set; }
        public Nullable<decimal> TotalWeight { get; set; }
        public string Remarks { get; set; }
    }
}
