//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Net4Courier.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InboundShipment
    {
        public int ShipmentID { get; set; }
        public string AWBNo { get; set; }
        public System.DateTime AWBDate { get; set; }
        public int CustomerID { get; set; }
        public string Consignor { get; set; }
        public string ConsignorAddress1_Building { get; set; }
        public string ConsignorPhone { get; set; }
        public string ConsignorCountryName { get; set; }
        public string ConsignorCityName { get; set; }
        public string ConsignorLocationName { get; set; }
        public string Consignee { get; set; }
        public string ConsigneeAddress1_Building { get; set; }
        public string ConsigneePhone { get; set; }
        public string ConsigneeCountryName { get; set; }
        public string ConsigneeCityName { get; set; }
        public Nullable<int> Pieces { get; set; }
        public Nullable<decimal> Weight { get; set; }
        public string CargoDescription { get; set; }
        public string BagNo { get; set; }
        public string Remarks { get; set; }
        public int MovementID { get; set; }
        public int ProductTypeID { get; set; }
        public int ParcelTypeID { get; set; }
        public Nullable<decimal> CourierCharge { get; set; }
        public Nullable<decimal> OtherCharge { get; set; }
        public Nullable<decimal> TaxPercent { get; set; }
        public Nullable<decimal> TaxAmount { get; set; }
        public Nullable<decimal> SurchargePercent { get; set; }
        public Nullable<decimal> SurchargeAmount { get; set; }
        public Nullable<decimal> NetTotal { get; set; }
        public Nullable<decimal> MaterialCost { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<int> PaymentModeId { get; set; }
        public Nullable<int> CurrencyID { get; set; }
        public int CourierStatusID { get; set; }
        public int StatusTypeId { get; set; }
        public int BranchID { get; set; }
        public Nullable<int> BATCHID { get; set; }
        public string EntrySource { get; set; }
        public int AcFinancialYearID { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> LastModifiedBy { get; set; }
        public Nullable<System.DateTime> LastModifiedDate { get; set; }
        public string ConsigneeLocationName { get; set; }
        public Nullable<int> CustomerRateID { get; set; }
        public Nullable<int> FAgentID { get; set; }
        public Nullable<decimal> CustomsValue { get; set; }
        public string MAWB { get; set; }
        public Nullable<int> TaxInvoiceID { get; set; }
        public Nullable<int> ManifestID { get; set; }
        public Nullable<int> QuickInscanID { get; set; }
        public Nullable<int> DRSID { get; set; }
        public Nullable<int> POD { get; set; }
        public Nullable<int> AgentInvoiceID { get; set; }
        public Nullable<decimal> ManifestWeight { get; set; }
        public string ConsignorContact { get; set; }
        public string ConsignorAddress2_Street { get; set; }
        public string ConsignorAddress3_PinCode { get; set; }
        public string ConsignorMobileNo { get; set; }
        public string ConsigneeContact { get; set; }
        public string ConsigneeAddress2_Street { get; set; }
        public string ConsigneeAddress3_PinCode { get; set; }
        public string ConsigneeMobileNo { get; set; }
        public string SpecialInstructions { get; set; }
        public Nullable<int> AcJournalID { get; set; }
        public Nullable<int> CODReceiptId { get; set; }
        public Nullable<int> DRRID { get; set; }
        public string ForwardingAWBNo { get; set; }
        public Nullable<decimal> ForwardingCharge { get; set; }
        public string Route { get; set; }
        public Nullable<int> SupplierInvoiceId { get; set; }
    }
}
