//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Net4Courier.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InScanMasterItem
    {
        public int ID { get; set; }
        public Nullable<int> InScanID { get; set; }
        public string BoxName { get; set; }
        public string Contents { get; set; }
        public Nullable<decimal> Qty { get; set; }
        public Nullable<decimal> Value { get; set; }
        public Nullable<decimal> WeightPerCarton { get; set; }
        public Nullable<decimal> TotalWeight { get; set; }
    }
}
