//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Net4Courier.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InScanInternational
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public InScanInternational()
        {
            this.InScanInternationalDeatils = new HashSet<InScanInternationalDeatil>();
        }
    
        public int InScanInternationalID { get; set; }
        public int FAgentID { get; set; }
        public string ForwardingAWBNo { get; set; }
        public System.DateTime ForwardingDate { get; set; }
        public double VerifiedWeight { get; set; }
        public decimal ForwardingCharge { get; set; }
        public bool StatusAssignment { get; set; }
        public string Flight { get; set; }
        public string BagNo { get; set; }
        public string RunNo { get; set; }
        public string CDNo { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public string Remarks { get; set; }
        public string DocumentNo { get; set; }
        public string MAWBNo { get; set; }
        public Nullable<System.DateTime> MAWBDate { get; set; }
        public Nullable<System.DateTime> FlightDate { get; set; }
        public Nullable<int> InScanID { get; set; }
        public Nullable<int> ShippingCountryID { get; set; }
        public Nullable<int> ShippingDepotID { get; set; }
        public Nullable<int> ReceivingCountryID { get; set; }
        public Nullable<int> ReceivingDepotID { get; set; }
        public Nullable<decimal> ForwardingAgentRate { get; set; }
        public Nullable<decimal> RevisedRate { get; set; }
        public Nullable<int> Carrier { get; set; }
        public Nullable<int> MAWB { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InScanInternationalDeatil> InScanInternationalDeatils { get; set; }
    }
}
