//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Net4Courier.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InScanInternationalDeatil
    {
        public int InScanInternationalDeatilID { get; set; }
        public int InScanID { get; set; }
        public int InscanInternationalID { get; set; }
        public Nullable<decimal> VerifiedWeight { get; set; }
        public Nullable<decimal> ForwardingCharge { get; set; }
        public Nullable<int> Type { get; set; }
    
        public virtual InScanInternational InScanInternational { get; set; }
        public virtual OtherCharge OtherCharge { get; set; }
    }
}
