//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Net4Courier.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ManifestCODReceiptDetail
    {
        public int ReceiptDetailID { get; set; }
        public int ReceiptID { get; set; }
        public Nullable<int> InboundShipmentID { get; set; }
        public string AWBNo { get; set; }
        public decimal COD { get; set; }
    
        public virtual ManifestCODReceipt ManifestCODReceipt { get; set; }
        public virtual ManifestCODReceipt ManifestCODReceipt1 { get; set; }
    }
}
