//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Net4Courier.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Manifest
    {
        public int ManifestID { get; set; }
        public string ManifestNo { get; set; }
        public System.DateTime ManifestDate { get; set; }
        public int InScanID { get; set; }
        public string AWBNo { get; set; }
        public int ShipperID { get; set; }
        public string Consignee { get; set; }
        public string Route { get; set; }
        public int ForwardingAgentID { get; set; }
        public string ForwardingAWBNo { get; set; }
        public bool StatusUpdated { get; set; }
        public Nullable<int> AcCompanyID { get; set; }
    }
}
