//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Net4Courier.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MaterialCostMaster
    {
        public int MCID { get; set; }
        public System.DateTime MCDate { get; set; }
        public int InScanID { get; set; }
        public decimal MaterialCost { get; set; }
        public Nullable<int> DRSID { get; set; }
        public Nullable<int> MCPVID { get; set; }
        public string Status { get; set; }
        public bool StatusClose { get; set; }
        public Nullable<int> DRRID { get; set; }
        public Nullable<decimal> MCReceivedAmt { get; set; }
        public Nullable<decimal> MCPayment { get; set; }
    }
}
