//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Net4Courier.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MCPaymentVoucher
    {
        public int MCPaymentVoucherID { get; set; }
        public string VoucherNo { get; set; }
        public Nullable<System.DateTime> PrintDate { get; set; }
        public Nullable<int> BranchID { get; set; }
        public Nullable<int> FYearID { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string Consignor { get; set; }
        public Nullable<int> TotalAWB { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
        public Nullable<int> DocumentNO { get; set; }
        public bool Closed { get; set; }
        public Nullable<System.DateTime> ClosedDate { get; set; }
        public Nullable<int> ClosedBy { get; set; }
        public bool IsClosed { get; set; }
        public bool IsDeleted { get; set; }
    }
}
