//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Net4Courier.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MenuAccessLevel
    {
        public long MenuAccessID { get; set; }
        public Nullable<int> MenuID { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<int> IsActive { get; set; }
        public Nullable<int> ParentID { get; set; }
        public Nullable<int> RoleID { get; set; }
        public bool IsView { get; set; }
        public bool IsAdd { get; set; }
        public bool IsModify { get; set; }
        public bool IsDelete { get; set; }
        public bool Isprint { get; set; }
    }
}
