//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Net4Courier.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OtherCharge
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OtherCharge()
        {
            this.InScanInternationalDeatils = new HashSet<InScanInternationalDeatil>();
            this.InscanOtherCharges = new HashSet<InscanOtherCharge>();
        }
    
        public int OtherChargeID { get; set; }
        public string OtherCharge1 { get; set; }
        public Nullable<int> AcHeadID { get; set; }
        public Nullable<int> AcCompanyID { get; set; }
        public Nullable<bool> statusinvoice { get; set; }
        public Nullable<decimal> SetAmount { get; set; }
        public Nullable<bool> TypePercent { get; set; }
        public bool Reimbursement { get; set; }
        public bool TaxApplicable { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InScanInternationalDeatil> InScanInternationalDeatils { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InscanOtherCharge> InscanOtherCharges { get; set; }
    }
}
