//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Net4Courier.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OtherChargeInvoiceDetail
    {
        public int OtherChargeInvoiceDetailID { get; set; }
        public Nullable<int> OtherChargeInvoiceID { get; set; }
        public Nullable<int> OtherChargeID { get; set; }
        public Nullable<int> AcHeadID { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> InscanID { get; set; }
    }
}
