//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Net4Courier.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OutstandingInvoiceDetail
    {
        public int OutstandingID { get; set; }
        public Nullable<int> InvoiceID { get; set; }
        public string InvoiceNo { get; set; }
        public string Status { get; set; }
        public string Remarks { get; set; }
        public string StatusInvoice { get; set; }
    }
}
