//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Net4Courier.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pallet
    {
        public int PalletID { get; set; }
        public Nullable<int> InscanID { get; set; }
        public string PalletNo { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<double> Weight { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public Nullable<int> DestinationID { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> AcCompanyID { get; set; }
    }
}
