//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Net4Courier.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ParcelType
    {
        public int ID { get; set; }
        public Nullable<int> ParcelTypeID { get; set; }
        public string ParcelType1 { get; set; }
        public bool DefaultType { get; set; }
    }
}
