//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Net4Courier.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PeriodLock
    {
        public int PeriodLockID { get; set; }
        public string Period { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public bool CurrentStatus { get; set; }
        public Nullable<System.DateTime> StatusChangeDate { get; set; }
        public Nullable<int> UserName { get; set; }
        public Nullable<int> FYearID { get; set; }
        public string Remarks { get; set; }
    }
}
