//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Net4Courier.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PODSignature
    {
        public int PODSignatureID { get; set; }
        public Nullable<int> PODID { get; set; }
        public Nullable<int> InscanID { get; set; }
        public Nullable<bool> statusUpdate { get; set; }
        public string SignatureImage { get; set; }
    }
}
