//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Net4Courier.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PrepaidAWB
    {
        public int PrepaidAWBID { get; set; }
        public System.DateTime TransDate { get; set; }
        public int CustomerID { get; set; }
        public int NoOfAWBs { get; set; }
        public decimal CourierCharge { get; set; }
        public decimal Total { get; set; }
        public int AcHeadID { get; set; }
        public string Reference { get; set; }
        public string Documentno { get; set; }
        public int AcCompanyID { get; set; }
        public Nullable<int> AcjournalID { get; set; }
        public int BranchID { get; set; }
        public string OriginLocation { get; set; }
        public string DestinationLocation { get; set; }
        public string BankName { get; set; }
        public string ChequeNo { get; set; }
        public Nullable<System.DateTime> ChequeDate { get; set; }
        public string StatusEntry { get; set; }
        public string AWBNOFrom { get; set; }
        public string AWBNOTo { get; set; }
        public Nullable<int> FYearId { get; set; }
        public Nullable<int> CreatedUserID { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedUserID { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public bool Prepaid { get; set; }
        public string PickupSubLocality { get; set; }
        public string DeliverySubLocality { get; set; }
        public string OriginPlaceID { get; set; }
        public string DestinationPlaceID { get; set; }
        public string Consignee { get; set; }
    }
}
