//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Net4Courier.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductType
    {
        public int ProductTypeID { get; set; }
        public string ProductName { get; set; }
        public int ParcelTypeID { get; set; }
        public int TransportModeID { get; set; }
        public bool CBMBasedCharges { get; set; }
        public Nullable<decimal> Length { get; set; }
        public Nullable<decimal> Width { get; set; }
        public Nullable<decimal> Height { get; set; }
        public Nullable<decimal> CBM { get; set; }
        public bool DefaultType { get; set; }
        public bool VolumeMetricBased { get; set; }
        public Nullable<decimal> VolumeWeight { get; set; }
        public bool CustomBox { get; set; }
    }
}
