//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Net4Courier.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchaseInvoiceDetail
    {
        public int PurchaseInvoiceDetailID { get; set; }
        public Nullable<int> PurchaseInvoiceID { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public Nullable<int> ItemUnitID { get; set; }
        public Nullable<decimal> Rate { get; set; }
        public Nullable<int> JobID { get; set; }
        public string Description { get; set; }
        public Nullable<int> DebitAcHeadID { get; set; }
        public string Details { get; set; }
    
        public virtual ItemUnit ItemUnit { get; set; }
        public virtual PurchaseInvoice PurchaseInvoice { get; set; }
    }
}
