//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Net4Courier.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuickInscanMaster
    {
        public int QuickInscanID { get; set; }
        public string InscanSheetNumber { get; set; }
        public Nullable<int> ReceivedByID { get; set; }
        public Nullable<int> CollectedByID { get; set; }
        public System.DateTime QuickInscanDateTime { get; set; }
        public Nullable<int> VehicleId { get; set; }
        public string DriverName { get; set; }
        public Nullable<int> BranchId { get; set; }
        public Nullable<int> DepotId { get; set; }
        public Nullable<int> AcCompanyId { get; set; }
        public Nullable<int> UserId { get; set; }
        public string Source { get; set; }
        public Nullable<int> AgentID { get; set; }
        public Nullable<int> AcFinancialYearID { get; set; }
        public bool OutScanReturned { get; set; }
        public Nullable<System.DateTime> CollectedDate { get; set; }
    }
}
