//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Net4Courier.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Quotation
    {
        public int QuotationID { get; set; }
        public int CustomerID { get; set; }
        public string QuotationNo { get; set; }
        public Nullable<System.DateTime> QuotationDate { get; set; }
        public Nullable<int> Version { get; set; }
        public string ContactPerson { get; set; }
        public string MobileNumber { get; set; }
        public Nullable<int> CurrencyId { get; set; }
        public string PaymentTerms { get; set; }
        public string TermsandConditions { get; set; }
        public string Salutation { get; set; }
        public string Remarks { get; set; }
        public Nullable<decimal> QuotationValue { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> Validity { get; set; }
        public string SubjectText { get; set; }
        public string ClientDetail { get; set; }
        public Nullable<int> AcFinancialYearID { get; set; }
        public Nullable<int> BranchID { get; set; }
        public bool IsDeleted { get; set; }
    }
}
