//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Net4Courier.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuotationDetail
    {
        public int QuotationDetailId { get; set; }
        public int QuotationID { get; set; }
        public string ItemDescription { get; set; }
        public Nullable<int> UOM { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public Nullable<decimal> Rate { get; set; }
        public Nullable<decimal> Value { get; set; }
        public string Remarks { get; set; }
        public string GroupName { get; set; }
    }
}
