//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Net4Courier.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReturnDetail
    {
        public int ReturnDetailID { get; set; }
        public int DRSDetailID { get; set; }
        public int EmployeeID { get; set; }
        public System.DateTime ReturnTime { get; set; }
        public string Remarks { get; set; }
    }
}
