//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Net4Courier.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShipmentInvoice
    {
        public int ShipmentInvoiceID { get; set; }
        public string InvoiceNo { get; set; }
        public Nullable<System.DateTime> InvoiceDate { get; set; }
        public Nullable<int> ShipmentImportID { get; set; }
        public Nullable<int> AcCompanyID { get; set; }
        public Nullable<int> AcJournalID { get; set; }
        public Nullable<decimal> InvoiceTotal { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> BranchId { get; set; }
        public Nullable<int> FYearId { get; set; }
        public string MAWB { get; set; }
        public bool IsOwn { get; set; }
        public Nullable<int> SupplierID { get; set; }
    }
}
