//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Net4Courier.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StaffNote
    {
        public int NotesId { get; set; }
        public int InScanId { get; set; }
        public int EmployeeId { get; set; }
        public string Notes { get; set; }
        public System.DateTime EntryDate { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> RecPayID { get; set; }
        public Nullable<int> PageTypeId { get; set; }
    }
}
