//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Net4Courier.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SupplierInvoiceStock
    {
        public int ID { get; set; }
        public Nullable<int> SupplierInvoiceID { get; set; }
        public Nullable<int> SupplierInvoiceDetailId { get; set; }
        public Nullable<int> SupplierID { get; set; }
        public Nullable<int> StockType { get; set; }
        public string BookNo { get; set; }
        public Nullable<int> AWBNOFrom { get; set; }
        public Nullable<int> AWBNOTo { get; set; }
        public Nullable<int> AWBCount { get; set; }
        public Nullable<int> Qty { get; set; }
        public Nullable<decimal> Rate { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string ItemSize { get; set; }
    }
}
