//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Net4Courier.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SupplierInvoiceAWB
    {
        public int ID { get; set; }
        public int SupplierInvoiceId { get; set; }
        public int SupplierInvoiceDetailId { get; set; }
        public int AcHeadId { get; set; }
        public int InScanID { get; set; }
        public Nullable<decimal> Amount { get; set; }
    }
}
