//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Net4Courier.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCustomerAdjustment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblCustomerAdjustment()
        {
            this.tblCustomerAdjustmentDetails = new HashSet<tblCustomerAdjustmentDetail>();
        }
    
        public int ID { get; set; }
        public string PaymentType { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public string ReferenceNo { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> AcJournalID { get; set; }
        public Nullable<int> FyearID { get; set; }
    
        public virtual AcJournalMaster AcJournalMaster { get; set; }
        public virtual CustomerMaster CustomerMaster { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblCustomerAdjustmentDetail> tblCustomerAdjustmentDetails { get; set; }
    }
}
