//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Net4Courier.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDeliveryAttempt
    {
        public int id { get; set; }
        public string image { get; set; }
        public System.DateTime date { get; set; }
        public Nullable<int> DRSID { get; set; }
        public Nullable<int> ReasonID { get; set; }
    }
}
