//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Net4Courier.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDepot
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblDepot()
        {
            this.tblStockIssues = new HashSet<tblStockIssue>();
            this.tblStockIssues1 = new HashSet<tblStockIssue>();
        }
    
        public int ID { get; set; }
        public Nullable<int> CountryID { get; set; }
        public Nullable<int> CityID { get; set; }
        public string Depot { get; set; }
        public Nullable<bool> IsOwn { get; set; }
        public Nullable<int> AgentID { get; set; }
        public Nullable<int> CompanyID { get; set; }
        public string CountryName { get; set; }
        public string CityName { get; set; }
        public Nullable<int> BranchID { get; set; }
    
        public virtual CityMaster CityMaster { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblStockIssue> tblStockIssues { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblStockIssue> tblStockIssues1 { get; set; }
    }
}
