//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Net4Courier.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblStockIssue
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblStockIssue()
        {
            this.tblStockIssueDetails = new HashSet<tblStockIssueDetail>();
        }
    
        public int ID { get; set; }
        public Nullable<System.DateTime> IssueDate { get; set; }
        public string FromAWBNo { get; set; }
        public string ToAWBNo { get; set; }
        public Nullable<int> IssueBy { get; set; }
        public Nullable<int> FromAgentID { get; set; }
        public Nullable<int> FromDepotID { get; set; }
        public Nullable<int> FromCourierID { get; set; }
        public Nullable<int> AgentID { get; set; }
        public Nullable<int> DepotID { get; set; }
        public Nullable<int> CourierID { get; set; }
        public string ReferenceNo { get; set; }
    
        public virtual tblDepot tblDepot { get; set; }
        public virtual tblDepot tblDepot1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblStockIssueDetail> tblStockIssueDetails { get; set; }
    }
}
