//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Net4Courier.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblStock
    {
        public int ID { get; set; }
        public Nullable<int> SupplierID { get; set; }
        public string InvoiceNo { get; set; }
        public Nullable<System.DateTime> PurchaseDate { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<int> TotalQuantity { get; set; }
        public string FromAWBNo { get; set; }
        public Nullable<short> Interval { get; set; }
        public string ToAWBNo { get; set; }
        public string ReferenceNo { get; set; }
    }
}
