//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Net4Courier.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblShipmentMode
    {
        public int ID { get; set; }
        public string ShipmentMode { get; set; }
        public string Prefix { get; set; }
        public bool ByDefault { get; set; }
    }
}
