//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Net4Courier.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSupplierAdjustment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblSupplierAdjustment()
        {
            this.tblSupplierAdjustmentDetails = new HashSet<tblSupplierAdjustmentDetail>();
        }
    
        public int ID { get; set; }
        public string PaymentType { get; set; }
        public Nullable<int> SupplierID { get; set; }
        public string ReferenceNo { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> AcJournalID { get; set; }
        public Nullable<int> FyearID { get; set; }
        public string Remarks { get; set; }
    
        public virtual AcFinancialYear AcFinancialYear { get; set; }
        public virtual AcJournalMaster AcJournalMaster { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblSupplierAdjustmentDetail> tblSupplierAdjustmentDetails { get; set; }
        public virtual SupplierMaster SupplierMaster { get; set; }
    }
}
