//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Net4Courier.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTaxConfiguration
    {
        public int ID { get; set; }
        public Nullable<decimal> Tax { get; set; }
        public Nullable<bool> CourierCharges { get; set; }
        public Nullable<bool> OtherCharges { get; set; }
        public Nullable<bool> ServiceCharges { get; set; }
        public Nullable<bool> PackingCharges { get; set; }
        public Nullable<bool> CollectionCharges { get; set; }
        public Nullable<bool> DeliveryCharges { get; set; }
        public Nullable<bool> Charges1 { get; set; }
        public Nullable<bool> Charges2 { get; set; }
        public Nullable<bool> Charges3 { get; set; }
    }
}
