//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Net4Courier.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZoneChart
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ZoneChart()
        {
            this.CustomerRates = new HashSet<CustomerRate>();
            this.CustomerRates1 = new HashSet<CustomerRate>();
            this.ForwardingAgentRates = new HashSet<ForwardingAgentRate>();
            this.ForwardingAgentRates1 = new HashSet<ForwardingAgentRate>();
        }
    
        public int ZoneChartID { get; set; }
        public int ZoneCategoryID { get; set; }
        public int ZoneID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomerRate> CustomerRates { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomerRate> CustomerRates1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ForwardingAgentRate> ForwardingAgentRates { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ForwardingAgentRate> ForwardingAgentRates1 { get; set; }
        public virtual ZoneCategory ZoneCategory { get; set; }
        public virtual ZoneCategory ZoneCategory1 { get; set; }
        public virtual ZoneMaster ZoneMaster { get; set; }
        public virtual ZoneMaster ZoneMaster1 { get; set; }
    }
}
