// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Net4Courier.Shared.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Net4Courier.Shared.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Net4Courier.Shared.Entities.Branch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AWBFormat")
                        .HasColumnType("text");

                    b.Property<string>("Address1")
                        .HasColumnType("text");

                    b.Property<string>("Address2")
                        .HasColumnType("text");

                    b.Property<string>("Address3")
                        .HasColumnType("text");

                    b.Property<string>("BranchPrefix")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("CODReceiptFormat")
                        .HasColumnType("text");

                    b.Property<string>("CODReceiptPrefix")
                        .HasColumnType("text");

                    b.Property<int>("CompanyId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("CurrentFinancialYearId")
                        .HasColumnType("integer");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("InvoiceFormat")
                        .HasColumnType("text");

                    b.Property<string>("InvoicePrefix")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("KeyPerson")
                        .HasColumnType("text");

                    b.Property<string>("MobileNo1")
                        .HasColumnType("text");

                    b.Property<string>("MobileNo2")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Phone")
                        .HasColumnType("text");

                    b.Property<bool>("TaxEnable")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("VATPercent")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("VATRegistrationNo")
                        .HasColumnType("text");

                    b.Property<string>("Website")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("CurrentFinancialYearId");

                    b.ToTable("branches", (string)null);
                });

            modelBuilder.Entity("Net4Courier.Shared.Entities.Company", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("AWBAlphaNumeric")
                        .HasColumnType("boolean");

                    b.Property<string>("AWBFormat")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("AcceptSystem")
                        .HasColumnType("boolean");

                    b.Property<string>("Address1")
                        .HasColumnType("text");

                    b.Property<string>("Address2")
                        .HasColumnType("text");

                    b.Property<string>("Address3")
                        .HasColumnType("text");

                    b.Property<byte[]>("CompanyLogo")
                        .HasColumnType("bytea");

                    b.Property<string>("CompanyPrefix")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<bool>("EnableAPI")
                        .HasColumnType("boolean");

                    b.Property<bool>("EnableCashCustomerInvoice")
                        .HasColumnType("boolean");

                    b.Property<string>("InvoiceFormat")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("InvoicePrefix")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("KeyPerson")
                        .HasColumnType("text");

                    b.Property<string>("LogoFileName")
                        .HasColumnType("text");

                    b.Property<string>("MobileNo1")
                        .HasColumnType("text");

                    b.Property<string>("MobileNo2")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Phone")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Website")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("companies", (string)null);
                });

            modelBuilder.Entity("Net4Courier.Shared.Entities.FinancialYear", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("BranchId")
                        .HasColumnType("integer");

                    b.Property<int>("CompanyId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FromDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsClosed")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsCurrent")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("ToDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("BranchId");

                    b.HasIndex("CompanyId");

                    b.ToTable("financial_years", (string)null);
                });

            modelBuilder.Entity("Net4Courier.Shared.Entities.Menu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Icon")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("ModuleName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("ParentId")
                        .HasColumnType("integer");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<string>("Url")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("menus", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 1, 15, 9, 31, 38, 819, DateTimeKind.Utc).AddTicks(3793),
                            Icon = "Dashboard",
                            IsActive = true,
                            ModuleName = "Dashboard",
                            Name = "Dashboard",
                            SortOrder = 1,
                            Url = "/"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 1, 15, 9, 31, 38, 819, DateTimeKind.Utc).AddTicks(3804),
                            Icon = "Settings",
                            IsActive = true,
                            ModuleName = "MasterData",
                            Name = "Master Data",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 1, 15, 9, 31, 38, 819, DateTimeKind.Utc).AddTicks(3807),
                            Icon = "Business",
                            IsActive = true,
                            ModuleName = "Companies",
                            Name = "Companies",
                            ParentId = 2,
                            SortOrder = 1,
                            Url = "/companies"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 1, 15, 9, 31, 38, 819, DateTimeKind.Utc).AddTicks(3810),
                            Icon = "AccountTree",
                            IsActive = true,
                            ModuleName = "Branches",
                            Name = "Branches",
                            ParentId = 2,
                            SortOrder = 2,
                            Url = "/branches"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2026, 1, 15, 9, 31, 38, 819, DateTimeKind.Utc).AddTicks(3813),
                            Icon = "People",
                            IsActive = true,
                            ModuleName = "Users",
                            Name = "Users",
                            ParentId = 2,
                            SortOrder = 3,
                            Url = "/users"
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2026, 1, 15, 9, 31, 38, 819, DateTimeKind.Utc).AddTicks(3815),
                            Icon = "AdminPanelSettings",
                            IsActive = true,
                            ModuleName = "Roles",
                            Name = "Roles",
                            ParentId = 2,
                            SortOrder = 4,
                            Url = "/roles"
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2026, 1, 15, 9, 31, 38, 819, DateTimeKind.Utc).AddTicks(3818),
                            Icon = "CalendarMonth",
                            IsActive = true,
                            ModuleName = "FinancialYears",
                            Name = "Financial Years",
                            ParentId = 2,
                            SortOrder = 5,
                            Url = "/financial-years"
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2026, 1, 15, 9, 31, 38, 819, DateTimeKind.Utc).AddTicks(3820),
                            Icon = "LocalShipping",
                            IsActive = true,
                            ModuleName = "Operations",
                            Name = "Operations",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2026, 1, 15, 9, 31, 38, 819, DateTimeKind.Utc).AddTicks(3822),
                            Icon = "Receipt",
                            IsActive = true,
                            ModuleName = "AWB",
                            Name = "AWB Entry",
                            ParentId = 8,
                            SortOrder = 1,
                            Url = "/awb"
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2026, 1, 15, 9, 31, 38, 819, DateTimeKind.Utc).AddTicks(3824),
                            Icon = "Inventory",
                            IsActive = true,
                            ModuleName = "Shipments",
                            Name = "Shipments",
                            ParentId = 8,
                            SortOrder = 2,
                            Url = "/shipments"
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2026, 1, 15, 9, 31, 38, 819, DateTimeKind.Utc).AddTicks(3827),
                            Icon = "AccountBalance",
                            IsActive = true,
                            ModuleName = "Accounts",
                            Name = "Accounts",
                            SortOrder = 4
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2026, 1, 15, 9, 31, 38, 819, DateTimeKind.Utc).AddTicks(3828),
                            Icon = "Description",
                            IsActive = true,
                            ModuleName = "Invoices",
                            Name = "Invoices",
                            ParentId = 11,
                            SortOrder = 1,
                            Url = "/invoices"
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2026, 1, 15, 9, 31, 38, 819, DateTimeKind.Utc).AddTicks(3831),
                            Icon = "ReceiptLong",
                            IsActive = true,
                            ModuleName = "Receipts",
                            Name = "Receipts",
                            ParentId = 11,
                            SortOrder = 2,
                            Url = "/receipts"
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(2026, 1, 15, 9, 31, 38, 819, DateTimeKind.Utc).AddTicks(3833),
                            Icon = "Assessment",
                            IsActive = true,
                            ModuleName = "Reports",
                            Name = "Reports",
                            SortOrder = 5,
                            Url = "/reports"
                        });
                });

            modelBuilder.Entity("Net4Courier.Shared.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("roles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 1, 15, 9, 31, 38, 819, DateTimeKind.Utc).AddTicks(3535),
                            Description = "Full system access",
                            IsActive = true,
                            Name = "Administrator"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 1, 15, 9, 31, 38, 819, DateTimeKind.Utc).AddTicks(3541),
                            Description = "Branch management access",
                            IsActive = true,
                            Name = "Manager"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 1, 15, 9, 31, 38, 819, DateTimeKind.Utc).AddTicks(3544),
                            Description = "Standard user access",
                            IsActive = true,
                            Name = "User"
                        });
                });

            modelBuilder.Entity("Net4Courier.Shared.Entities.RolePermission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("CanCreate")
                        .HasColumnType("boolean");

                    b.Property<bool>("CanDelete")
                        .HasColumnType("boolean");

                    b.Property<bool>("CanEdit")
                        .HasColumnType("boolean");

                    b.Property<bool>("CanView")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ModuleName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RoleId", "ModuleName")
                        .IsUnique();

                    b.ToTable("role_permissions", (string)null);
                });

            modelBuilder.Entity("Net4Courier.Shared.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("DefaultBranchId")
                        .HasColumnType("integer");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsLoggedIn")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LoginExpiryDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .HasColumnType("text");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("DefaultBranchId");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Net4Courier.Shared.Entities.UserBranch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BranchId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BranchId");

                    b.HasIndex("UserId", "BranchId")
                        .IsUnique();

                    b.ToTable("user_branches", (string)null);
                });

            modelBuilder.Entity("Net4Courier.Shared.Entities.Branch", b =>
                {
                    b.HasOne("Net4Courier.Shared.Entities.Company", "Company")
                        .WithMany("Branches")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Net4Courier.Shared.Entities.FinancialYear", "CurrentFinancialYear")
                        .WithMany()
                        .HasForeignKey("CurrentFinancialYearId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Company");

                    b.Navigation("CurrentFinancialYear");
                });

            modelBuilder.Entity("Net4Courier.Shared.Entities.FinancialYear", b =>
                {
                    b.HasOne("Net4Courier.Shared.Entities.Branch", "Branch")
                        .WithMany()
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Net4Courier.Shared.Entities.Company", "Company")
                        .WithMany("FinancialYears")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Branch");

                    b.Navigation("Company");
                });

            modelBuilder.Entity("Net4Courier.Shared.Entities.Menu", b =>
                {
                    b.HasOne("Net4Courier.Shared.Entities.Menu", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("Net4Courier.Shared.Entities.RolePermission", b =>
                {
                    b.HasOne("Net4Courier.Shared.Entities.Role", "Role")
                        .WithMany("Permissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Net4Courier.Shared.Entities.User", b =>
                {
                    b.HasOne("Net4Courier.Shared.Entities.Branch", "DefaultBranch")
                        .WithMany("Users")
                        .HasForeignKey("DefaultBranchId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Net4Courier.Shared.Entities.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DefaultBranch");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Net4Courier.Shared.Entities.UserBranch", b =>
                {
                    b.HasOne("Net4Courier.Shared.Entities.Branch", "Branch")
                        .WithMany()
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Net4Courier.Shared.Entities.User", "User")
                        .WithMany("UserBranches")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Branch");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Net4Courier.Shared.Entities.Branch", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("Net4Courier.Shared.Entities.Company", b =>
                {
                    b.Navigation("Branches");

                    b.Navigation("FinancialYears");
                });

            modelBuilder.Entity("Net4Courier.Shared.Entities.Menu", b =>
                {
                    b.Navigation("Children");
                });

            modelBuilder.Entity("Net4Courier.Shared.Entities.Role", b =>
                {
                    b.Navigation("Permissions");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("Net4Courier.Shared.Entities.User", b =>
                {
                    b.Navigation("UserBranches");
                });
#pragma warning restore 612, 618
        }
    }
}
