using Net4Courier.Kernel.Entities;
using Net4Courier.Kernel.Enums;

namespace Net4Courier.Operations.Entities;

public class InscanMaster : AuditableEntity
{
    public string AWBNo { get; set; } = string.Empty;
    public DateTime TransactionDate { get; set; }
    public long? FinancialYearId { get; set; }
    public long? CompanyId { get; set; }
    public long? BranchId { get; set; }
    public long? DepotId { get; set; }
    public long? CustomerId { get; set; }
    
    public string? Consignor { get; set; }
    public string? ConsignorContact { get; set; }
    public string? ConsignorPhone { get; set; }
    public string? ConsignorMobile { get; set; }
    public string? ConsignorAddress1 { get; set; }
    public string? ConsignorAddress2 { get; set; }
    public string? ConsignorCity { get; set; }
    public string? ConsignorState { get; set; }
    public string? ConsignorCountry { get; set; }
    public string? ConsignorPostalCode { get; set; }
    public string? ConsignorLocation { get; set; }
    public long? OriginPortId { get; set; }
    public string? OriginPortCode { get; set; }
    
    public string? Consignee { get; set; }
    public string? ConsigneeContact { get; set; }
    public string? ConsigneePhone { get; set; }
    public string? ConsigneeMobile { get; set; }
    public string? ConsigneeAddress1 { get; set; }
    public string? ConsigneeAddress2 { get; set; }
    public string? ConsigneeCity { get; set; }
    public string? ConsigneeState { get; set; }
    public string? ConsigneeCountry { get; set; }
    public string? ConsigneePostalCode { get; set; }
    public string? ConsigneeLocation { get; set; }
    public long? DestinationPortId { get; set; }
    public string? DestinationPortCode { get; set; }
    
    public int? Pieces { get; set; }
    public decimal? Weight { get; set; }
    public decimal? StatedWeight { get; set; }
    public decimal? VerifiedWeight { get; set; }
    public decimal? VolumetricWeight { get; set; }
    public decimal? ChargeableWeight { get; set; }
    public decimal? Length { get; set; }
    public decimal? Width { get; set; }
    public decimal? Height { get; set; }
    public decimal? CBM { get; set; }
    
    public string? CargoDescription { get; set; }
    public string? SpecialInstructions { get; set; }
    public string? HandlingInstructions { get; set; }
    public string? Remarks { get; set; }
    
    public CourierStatus CourierStatusId { get; set; } = CourierStatus.Pending;
    public int? StatusTypeId { get; set; }
    public int? SubReasonId { get; set; }
    public PaymentMode PaymentModeId { get; set; } = PaymentMode.Prepaid;
    public MovementType MovementTypeId { get; set; } = MovementType.Domestic;
    public DocumentType DocumentTypeId { get; set; } = DocumentType.Document;
    public long? ShipmentModeId { get; set; }
    public int? ProductTypeId { get; set; }
    public int? ParcelTypeId { get; set; }
    public int? TypeOfGoodId { get; set; }
    
    public decimal? CourierCharge { get; set; }
    public decimal? OtherCharge { get; set; }
    public decimal? FuelSurcharge { get; set; }
    public decimal? MaterialCost { get; set; }
    public decimal? CustomsValue { get; set; }
    public string? Currency { get; set; }
    public decimal? TaxPercent { get; set; }
    public decimal? TaxAmount { get; set; }
    public decimal? SurchargePercent { get; set; }
    public decimal? SurchargeAmount { get; set; }
    public decimal? Discount { get; set; }
    public decimal? NetTotal { get; set; }
    
    public long? InvoiceId { get; set; }
    public long? DRSId { get; set; }
    public long? PODId { get; set; }
    public long? ManifestId { get; set; }
    public long? QuickInscanId { get; set; }
    public long? BatchId { get; set; }
    public long? ForwardingAgentId { get; set; }
    public string? ForwardingAWBNo { get; set; }
    public decimal? ForwardingCharge { get; set; }
    public decimal? SpotRate { get; set; }
    public decimal? MarginPercent { get; set; }
    public decimal? ManifestWeight { get; set; }
    
    public bool IsNCND { get; set; }
    public bool IsCashOnly { get; set; }
    public bool IsChequeOnly { get; set; }
    public bool IsCollectMaterial { get; set; }
    public bool IsDOCopyBack { get; set; }
    
    public int? AssignedEmployeeId { get; set; }
    public int? PickedUpEmployeeId { get; set; }
    public int? ReceivedByEmployeeId { get; set; }
    public string? PickedBy { get; set; }
    public string? ReceivedBy { get; set; }
    public DateTime? PickupRequestDate { get; set; }
    public DateTime? PickedUpDate { get; set; }
    public DateTime? DeliveredDate { get; set; }
    public string? DeliveredTo { get; set; }
    public string? PODSignature { get; set; }
    
    public bool IsAutoGenerated { get; set; }
    public bool IsProcessed { get; set; }
    public bool IsReturnedToConsignor { get; set; }
    public bool IsCOD { get; set; }
    public decimal? CODAmount { get; set; }
    public bool CODCollected { get; set; }
    
    public string? DeviceId { get; set; }
    public int? EntrySource { get; set; }
    public string? JobCode { get; set; }
    public string? ReferenceNo { get; set; }
    
    public bool IsRTS { get; set; }
    public long? OriginalShipmentId { get; set; }
    public RTSChargeMode? RTSChargeMode { get; set; }
    public DateTime? RTSCreatedAt { get; set; }
    public long? RTSCreatedByUserId { get; set; }
    public string? RTSCreatedByUserName { get; set; }
    public string? RTSReason { get; set; }
    
    public long? PickupRequestId { get; set; }
    public long? PickupRequestShipmentId { get; set; }
    
    public long? MAWBId { get; set; }
    public long? MAWBBagId { get; set; }
    public string? MAWBNo { get; set; }
    public string? BagNo { get; set; }
    public DateTime? BaggedAt { get; set; }
    public long? BaggedByUserId { get; set; }
    public string? BaggedByUserName { get; set; }
    
    public bool IsOnHold { get; set; }
    public string? HoldReason { get; set; }
    public DateTime? HoldDate { get; set; }
    public long? HoldByUserId { get; set; }
    public string? HoldByUserName { get; set; }
    public DateTime? HoldReleasedDate { get; set; }
    public long? HoldReleasedByUserId { get; set; }
    public string? HoldReleasedByUserName { get; set; }
    
    public virtual MasterAirwaybill? MAWB { get; set; }
    public virtual MAWBBag? MAWBBag { get; set; }
    
    public virtual InscanMaster? OriginalShipment { get; set; }
    public virtual ICollection<InscanMaster> RTSShipments { get; set; } = new List<InscanMaster>();
    
    public virtual ICollection<InscanMasterItem> Items { get; set; } = new List<InscanMasterItem>();
    public virtual ICollection<AWBTracking> TrackingHistory { get; set; } = new List<AWBTracking>();
    public virtual ICollection<AWBOtherCharge> OtherCharges { get; set; } = new List<AWBOtherCharge>();
    public virtual ICollection<ShipmentNote> Notes { get; set; } = new List<ShipmentNote>();
}
