-- InscanMasters Hold Columns - Run these one at a time
ALTER TABLE "InscanMasters" ADD COLUMN IF NOT EXISTS "IsOnHold" BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE "InscanMasters" ADD COLUMN IF NOT EXISTS "HoldReason" VARCHAR(500);
ALTER TABLE "InscanMasters" ADD COLUMN IF NOT EXISTS "HoldDate" TIMESTAMP WITH TIME ZONE;
ALTER TABLE "InscanMasters" ADD COLUMN IF NOT EXISTS "HoldByUserId" BIGINT;
ALTER TABLE "InscanMasters" ADD COLUMN IF NOT EXISTS "HoldByUserName" VARCHAR(100);
ALTER TABLE "InscanMasters" ADD COLUMN IF NOT EXISTS "HoldReleasedDate" TIMESTAMP WITH TIME ZONE;
ALTER TABLE "InscanMasters" ADD COLUMN IF NOT EXISTS "HoldReleasedByUserId" BIGINT;
ALTER TABLE "InscanMasters" ADD COLUMN IF NOT EXISTS "HoldReleasedByUserName" VARCHAR(100);
