-- Production Schema Sync Script
-- This script adds potentially missing columns to EXISTING tables
-- Safe to run multiple times - uses ADD COLUMN IF NOT EXISTS
-- Download this file from Files panel and run on production database
-- NOTE: This does NOT create tables or modify primary keys

-- ============================================
-- InscanMasters (AWB/Shipment Master Table)
-- ============================================
ALTER TABLE "InscanMasters" ADD COLUMN IF NOT EXISTS "AWBNo" VARCHAR(50);
ALTER TABLE "InscanMasters" ADD COLUMN IF NOT EXISTS "TransactionDate" TIMESTAMP WITH TIME ZONE;
ALTER TABLE "InscanMasters" ADD COLUMN IF NOT EXISTS "FinancialYearId" BIGINT;
ALTER TABLE "InscanMasters" ADD COLUMN IF NOT EXISTS "CompanyId" BIGINT;
ALTER TABLE "InscanMasters" ADD COLUMN IF NOT EXISTS "BranchId" BIGINT;
ALTER TABLE "InscanMasters" ADD COLUMN IF NOT EXISTS "DepotId" BIGINT;
ALTER TABLE "InscanMasters" ADD COLUMN IF NOT EXISTS "CustomerId" BIGINT;
ALTER TABLE "InscanMasters" ADD COLUMN IF NOT EXISTS "Consignor" VARCHAR(200);
ALTER TABLE "InscanMasters" ADD COLUMN IF NOT EXISTS "ConsignorContact" VARCHAR(100);
ALTER TABLE "InscanMasters" ADD COLUMN IF NOT EXISTS "ConsignorPhone" VARCHAR(50);
ALTER TABLE "InscanMasters" ADD COLUMN IF NOT EXISTS "ConsignorMobile" VARCHAR(50);
ALTER TABLE "InscanMasters" ADD COLUMN IF NOT EXISTS "ConsignorAddress1" VARCHAR(500);
ALTER TABLE "InscanMasters" ADD COLUMN IF NOT EXISTS "ConsignorAddress2" VARCHAR(500);
ALTER TABLE "InscanMasters" ADD COLUMN IF NOT EXISTS "ConsignorCity" VARCHAR(100);
ALTER TABLE "InscanMasters" ADD COLUMN IF NOT EXISTS "ConsignorState" VARCHAR(100);
ALTER TABLE "InscanMasters" ADD COLUMN IF NOT EXISTS "ConsignorCountry" VARCHAR(100);
ALTER TABLE "InscanMasters" ADD COLUMN IF NOT EXISTS "ConsignorPostalCode" VARCHAR(20);
ALTER TABLE "InscanMasters" ADD COLUMN IF NOT EXISTS "ConsignorLocation" VARCHAR(100);
ALTER TABLE "InscanMasters" ADD COLUMN IF NOT EXISTS "OriginPortId" BIGINT;
ALTER TABLE "InscanMasters" ADD COLUMN IF NOT EXISTS "OriginPortCode" VARCHAR(20);
ALTER TABLE "InscanMasters" ADD COLUMN IF NOT EXISTS "Consignee" VARCHAR(200);
ALTER TABLE "InscanMasters" ADD COLUMN IF NOT EXISTS "ConsigneeContact" VARCHAR(100);
ALTER TABLE "InscanMasters" ADD COLUMN IF NOT EXISTS "ConsigneePhone" VARCHAR(50);
ALTER TABLE "InscanMasters" ADD COLUMN IF NOT EXISTS "ConsigneeMobile" VARCHAR(50);
ALTER TABLE "InscanMasters" ADD COLUMN IF NOT EXISTS "ConsigneeAddress1" VARCHAR(500);
ALTER TABLE "InscanMasters" ADD COLUMN IF NOT EXISTS "ConsigneeAddress2" VARCHAR(500);
ALTER TABLE "InscanMasters" ADD COLUMN IF NOT EXISTS "ConsigneeCity" VARCHAR(100);
ALTER TABLE "InscanMasters" ADD COLUMN IF NOT EXISTS "ConsigneeState" VARCHAR(100);
ALTER TABLE "InscanMasters" ADD COLUMN IF NOT EXISTS "ConsigneeCountry" VARCHAR(100);
ALTER TABLE "InscanMasters" ADD COLUMN IF NOT EXISTS "ConsigneePostalCode" VARCHAR(20);
ALTER TABLE "InscanMasters" ADD COLUMN IF NOT EXISTS "ConsigneeLocation" VARCHAR(100);
ALTER TABLE "InscanMasters" ADD COLUMN IF NOT EXISTS "DestinationPortId" BIGINT;
ALTER TABLE "InscanMasters" ADD COLUMN IF NOT EXISTS "DestinationPortCode" VARCHAR(20);
ALTER TABLE "InscanMasters" ADD COLUMN IF NOT EXISTS "Pieces" INT;
ALTER TABLE "InscanMasters" ADD COLUMN IF NOT EXISTS "Weight" DECIMAL(18,3);
ALTER TABLE "InscanMasters" ADD COLUMN IF NOT EXISTS "StatedWeight" DECIMAL(18,3);
ALTER TABLE "InscanMasters" ADD COLUMN IF NOT EXISTS "VerifiedWeight" DECIMAL(18,3);
ALTER TABLE "InscanMasters" ADD COLUMN IF NOT EXISTS "VolumetricWeight" DECIMAL(18,3);
ALTER TABLE "InscanMasters" ADD COLUMN IF NOT EXISTS "ChargeableWeight" DECIMAL(18,3);
ALTER TABLE "InscanMasters" ADD COLUMN IF NOT EXISTS "Length" DECIMAL(18,3);
ALTER TABLE "InscanMasters" ADD COLUMN IF NOT EXISTS "Width" DECIMAL(18,3);
ALTER TABLE "InscanMasters" ADD COLUMN IF NOT EXISTS "Height" DECIMAL(18,3);
ALTER TABLE "InscanMasters" ADD COLUMN IF NOT EXISTS "CBM" DECIMAL(18,3);
ALTER TABLE "InscanMasters" ADD COLUMN IF NOT EXISTS "CargoDescription" VARCHAR(500);
ALTER TABLE "InscanMasters" ADD COLUMN IF NOT EXISTS "SpecialInstructions" VARCHAR(500);
ALTER TABLE "InscanMasters" ADD COLUMN IF NOT EXISTS "HandlingInstructions" VARCHAR(500);
ALTER TABLE "InscanMasters" ADD COLUMN IF NOT EXISTS "Remarks" VARCHAR(500);
ALTER TABLE "InscanMasters" ADD COLUMN IF NOT EXISTS "CourierStatusId" INT DEFAULT 0;
ALTER TABLE "InscanMasters" ADD COLUMN IF NOT EXISTS "StatusTypeId" INT;
ALTER TABLE "InscanMasters" ADD COLUMN IF NOT EXISTS "SubReasonId" INT;
ALTER TABLE "InscanMasters" ADD COLUMN IF NOT EXISTS "PaymentModeId" INT DEFAULT 0;
ALTER TABLE "InscanMasters" ADD COLUMN IF NOT EXISTS "MovementTypeId" INT DEFAULT 1;
ALTER TABLE "InscanMasters" ADD COLUMN IF NOT EXISTS "DocumentTypeId" INT DEFAULT 1;
ALTER TABLE "InscanMasters" ADD COLUMN IF NOT EXISTS "ShipmentModeId" BIGINT;
ALTER TABLE "InscanMasters" ADD COLUMN IF NOT EXISTS "ProductTypeId" INT;
ALTER TABLE "InscanMasters" ADD COLUMN IF NOT EXISTS "ParcelTypeId" INT;
ALTER TABLE "InscanMasters" ADD COLUMN IF NOT EXISTS "TypeOfGoodId" INT;
ALTER TABLE "InscanMasters" ADD COLUMN IF NOT EXISTS "CourierCharge" DECIMAL(18,2);
ALTER TABLE "InscanMasters" ADD COLUMN IF NOT EXISTS "OtherCharge" DECIMAL(18,2);
ALTER TABLE "InscanMasters" ADD COLUMN IF NOT EXISTS "FuelSurcharge" DECIMAL(18,2);
ALTER TABLE "InscanMasters" ADD COLUMN IF NOT EXISTS "MaterialCost" DECIMAL(18,2);
ALTER TABLE "InscanMasters" ADD COLUMN IF NOT EXISTS "CustomsValue" DECIMAL(18,2);
ALTER TABLE "InscanMasters" ADD COLUMN IF NOT EXISTS "Currency" VARCHAR(10);
ALTER TABLE "InscanMasters" ADD COLUMN IF NOT EXISTS "TaxPercent" DECIMAL(18,2);
ALTER TABLE "InscanMasters" ADD COLUMN IF NOT EXISTS "TaxAmount" DECIMAL(18,2);
ALTER TABLE "InscanMasters" ADD COLUMN IF NOT EXISTS "SurchargePercent" DECIMAL(18,2);
ALTER TABLE "InscanMasters" ADD COLUMN IF NOT EXISTS "SurchargeAmount" DECIMAL(18,2);
ALTER TABLE "InscanMasters" ADD COLUMN IF NOT EXISTS "Discount" DECIMAL(18,2);
ALTER TABLE "InscanMasters" ADD COLUMN IF NOT EXISTS "NetTotal" DECIMAL(18,2);
ALTER TABLE "InscanMasters" ADD COLUMN IF NOT EXISTS "InvoiceId" BIGINT;
ALTER TABLE "InscanMasters" ADD COLUMN IF NOT EXISTS "DRSId" BIGINT;
ALTER TABLE "InscanMasters" ADD COLUMN IF NOT EXISTS "PODId" BIGINT;
ALTER TABLE "InscanMasters" ADD COLUMN IF NOT EXISTS "ManifestId" BIGINT;
ALTER TABLE "InscanMasters" ADD COLUMN IF NOT EXISTS "QuickInscanId" BIGINT;
ALTER TABLE "InscanMasters" ADD COLUMN IF NOT EXISTS "QuickInscanMasterId" BIGINT;
ALTER TABLE "InscanMasters" ADD COLUMN IF NOT EXISTS "BatchId" BIGINT;
ALTER TABLE "InscanMasters" ADD COLUMN IF NOT EXISTS "ForwardingAgentId" BIGINT;
ALTER TABLE "InscanMasters" ADD COLUMN IF NOT EXISTS "ForwardingAWBNo" VARCHAR(50);
ALTER TABLE "InscanMasters" ADD COLUMN IF NOT EXISTS "ForwardingCharge" DECIMAL(18,2);
ALTER TABLE "InscanMasters" ADD COLUMN IF NOT EXISTS "SpotRate" DECIMAL(18,2);
ALTER TABLE "InscanMasters" ADD COLUMN IF NOT EXISTS "MarginPercent" DECIMAL(18,2);
ALTER TABLE "InscanMasters" ADD COLUMN IF NOT EXISTS "ManifestWeight" DECIMAL(18,3);
ALTER TABLE "InscanMasters" ADD COLUMN IF NOT EXISTS "IsNCND" BOOLEAN DEFAULT FALSE;
ALTER TABLE "InscanMasters" ADD COLUMN IF NOT EXISTS "IsCashOnly" BOOLEAN DEFAULT FALSE;
ALTER TABLE "InscanMasters" ADD COLUMN IF NOT EXISTS "IsChequeOnly" BOOLEAN DEFAULT FALSE;
ALTER TABLE "InscanMasters" ADD COLUMN IF NOT EXISTS "IsCollectMaterial" BOOLEAN DEFAULT FALSE;
ALTER TABLE "InscanMasters" ADD COLUMN IF NOT EXISTS "IsDOCopyBack" BOOLEAN DEFAULT FALSE;
ALTER TABLE "InscanMasters" ADD COLUMN IF NOT EXISTS "AssignedEmployeeId" INT;
ALTER TABLE "InscanMasters" ADD COLUMN IF NOT EXISTS "PickedUpEmployeeId" INT;
ALTER TABLE "InscanMasters" ADD COLUMN IF NOT EXISTS "ReceivedByEmployeeId" INT;
ALTER TABLE "InscanMasters" ADD COLUMN IF NOT EXISTS "PickedBy" VARCHAR(100);
ALTER TABLE "InscanMasters" ADD COLUMN IF NOT EXISTS "ReceivedBy" VARCHAR(100);
ALTER TABLE "InscanMasters" ADD COLUMN IF NOT EXISTS "PickupRequestDate" TIMESTAMP WITH TIME ZONE;
ALTER TABLE "InscanMasters" ADD COLUMN IF NOT EXISTS "PickedUpDate" TIMESTAMP WITH TIME ZONE;
ALTER TABLE "InscanMasters" ADD COLUMN IF NOT EXISTS "DeliveredDate" TIMESTAMP WITH TIME ZONE;
ALTER TABLE "InscanMasters" ADD COLUMN IF NOT EXISTS "DeliveredTo" VARCHAR(200);
ALTER TABLE "InscanMasters" ADD COLUMN IF NOT EXISTS "PODSignature" VARCHAR(500);
ALTER TABLE "InscanMasters" ADD COLUMN IF NOT EXISTS "IsAutoGenerated" BOOLEAN DEFAULT FALSE;
ALTER TABLE "InscanMasters" ADD COLUMN IF NOT EXISTS "IsProcessed" BOOLEAN DEFAULT FALSE;
ALTER TABLE "InscanMasters" ADD COLUMN IF NOT EXISTS "IsReturnedToConsignor" BOOLEAN DEFAULT FALSE;
ALTER TABLE "InscanMasters" ADD COLUMN IF NOT EXISTS "IsCOD" BOOLEAN DEFAULT FALSE;
ALTER TABLE "InscanMasters" ADD COLUMN IF NOT EXISTS "CODAmount" DECIMAL(18,2);
ALTER TABLE "InscanMasters" ADD COLUMN IF NOT EXISTS "CODCollected" BOOLEAN DEFAULT FALSE;
ALTER TABLE "InscanMasters" ADD COLUMN IF NOT EXISTS "DutyVatAmount" DECIMAL(18,2);
ALTER TABLE "InscanMasters" ADD COLUMN IF NOT EXISTS "DeviceId" VARCHAR(100);
ALTER TABLE "InscanMasters" ADD COLUMN IF NOT EXISTS "EntrySource" INT;
ALTER TABLE "InscanMasters" ADD COLUMN IF NOT EXISTS "JobCode" VARCHAR(50);
ALTER TABLE "InscanMasters" ADD COLUMN IF NOT EXISTS "ReferenceNo" VARCHAR(100);
ALTER TABLE "InscanMasters" ADD COLUMN IF NOT EXISTS "BarcodeImage" BYTEA;
ALTER TABLE "InscanMasters" ADD COLUMN IF NOT EXISTS "BarcodeImageVertical" BYTEA;
ALTER TABLE "InscanMasters" ADD COLUMN IF NOT EXISTS "IsRTS" BOOLEAN DEFAULT FALSE;
ALTER TABLE "InscanMasters" ADD COLUMN IF NOT EXISTS "OriginalShipmentId" BIGINT;
ALTER TABLE "InscanMasters" ADD COLUMN IF NOT EXISTS "RTSChargeMode" INT;
ALTER TABLE "InscanMasters" ADD COLUMN IF NOT EXISTS "RTSCreatedAt" TIMESTAMP WITH TIME ZONE;
ALTER TABLE "InscanMasters" ADD COLUMN IF NOT EXISTS "RTSCreatedByUserId" BIGINT;
ALTER TABLE "InscanMasters" ADD COLUMN IF NOT EXISTS "RTSCreatedByUserName" VARCHAR(100);
ALTER TABLE "InscanMasters" ADD COLUMN IF NOT EXISTS "RTSReason" VARCHAR(500);
ALTER TABLE "InscanMasters" ADD COLUMN IF NOT EXISTS "PickupRequestId" BIGINT;
ALTER TABLE "InscanMasters" ADD COLUMN IF NOT EXISTS "PickupRequestShipmentId" BIGINT;
ALTER TABLE "InscanMasters" ADD COLUMN IF NOT EXISTS "MAWBId" BIGINT;
ALTER TABLE "InscanMasters" ADD COLUMN IF NOT EXISTS "MAWBBagId" BIGINT;
ALTER TABLE "InscanMasters" ADD COLUMN IF NOT EXISTS "MAWBNo" VARCHAR(50);
ALTER TABLE "InscanMasters" ADD COLUMN IF NOT EXISTS "BagNo" VARCHAR(50);
ALTER TABLE "InscanMasters" ADD COLUMN IF NOT EXISTS "BaggedAt" TIMESTAMP WITH TIME ZONE;
ALTER TABLE "InscanMasters" ADD COLUMN IF NOT EXISTS "BaggedByUserId" BIGINT;
ALTER TABLE "InscanMasters" ADD COLUMN IF NOT EXISTS "BaggedByUserName" VARCHAR(100);
ALTER TABLE "InscanMasters" ADD COLUMN IF NOT EXISTS "IsOnHold" BOOLEAN DEFAULT FALSE;
ALTER TABLE "InscanMasters" ADD COLUMN IF NOT EXISTS "HoldReason" VARCHAR(500);
ALTER TABLE "InscanMasters" ADD COLUMN IF NOT EXISTS "HoldDate" TIMESTAMP WITH TIME ZONE;
ALTER TABLE "InscanMasters" ADD COLUMN IF NOT EXISTS "HoldByUserId" BIGINT;
ALTER TABLE "InscanMasters" ADD COLUMN IF NOT EXISTS "HoldByUserName" VARCHAR(100);
ALTER TABLE "InscanMasters" ADD COLUMN IF NOT EXISTS "HoldReleasedDate" TIMESTAMP WITH TIME ZONE;
ALTER TABLE "InscanMasters" ADD COLUMN IF NOT EXISTS "HoldReleasedByUserId" BIGINT;
ALTER TABLE "InscanMasters" ADD COLUMN IF NOT EXISTS "HoldReleasedByUserName" VARCHAR(100);
ALTER TABLE "InscanMasters" ADD COLUMN IF NOT EXISTS "IsActive" BOOLEAN DEFAULT TRUE;
ALTER TABLE "InscanMasters" ADD COLUMN IF NOT EXISTS "IsDeleted" BOOLEAN DEFAULT FALSE;
ALTER TABLE "InscanMasters" ADD COLUMN IF NOT EXISTS "IsDemo" BOOLEAN DEFAULT FALSE;
ALTER TABLE "InscanMasters" ADD COLUMN IF NOT EXISTS "CreatedAt" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "InscanMasters" ADD COLUMN IF NOT EXISTS "ModifiedAt" TIMESTAMP WITH TIME ZONE;
ALTER TABLE "InscanMasters" ADD COLUMN IF NOT EXISTS "CreatedBy" INT;
ALTER TABLE "InscanMasters" ADD COLUMN IF NOT EXISTS "ModifiedBy" INT;
ALTER TABLE "InscanMasters" ADD COLUMN IF NOT EXISTS "CreatedByName" VARCHAR(200);
ALTER TABLE "InscanMasters" ADD COLUMN IF NOT EXISTS "ModifiedByName" VARCHAR(200);

-- ============================================
-- ShipmentStatusHistories
-- ============================================
ALTER TABLE "ShipmentStatusHistories" ADD COLUMN IF NOT EXISTS "InscanMasterId" BIGINT;
ALTER TABLE "ShipmentStatusHistories" ADD COLUMN IF NOT EXISTS "StatusId" BIGINT;
ALTER TABLE "ShipmentStatusHistories" ADD COLUMN IF NOT EXISTS "StatusGroupId" BIGINT;
ALTER TABLE "ShipmentStatusHistories" ADD COLUMN IF NOT EXISTS "EventType" VARCHAR(100);
ALTER TABLE "ShipmentStatusHistories" ADD COLUMN IF NOT EXISTS "EventRefId" BIGINT;
ALTER TABLE "ShipmentStatusHistories" ADD COLUMN IF NOT EXISTS "EventRefType" VARCHAR(100);
ALTER TABLE "ShipmentStatusHistories" ADD COLUMN IF NOT EXISTS "BranchId" BIGINT;
ALTER TABLE "ShipmentStatusHistories" ADD COLUMN IF NOT EXISTS "LocationName" VARCHAR(200);
ALTER TABLE "ShipmentStatusHistories" ADD COLUMN IF NOT EXISTS "UserId" BIGINT;
ALTER TABLE "ShipmentStatusHistories" ADD COLUMN IF NOT EXISTS "UserName" VARCHAR(200);
ALTER TABLE "ShipmentStatusHistories" ADD COLUMN IF NOT EXISTS "Remarks" VARCHAR(500);
ALTER TABLE "ShipmentStatusHistories" ADD COLUMN IF NOT EXISTS "ChangedAt" TIMESTAMP WITH TIME ZONE;
ALTER TABLE "ShipmentStatusHistories" ADD COLUMN IF NOT EXISTS "IsAutomatic" BOOLEAN DEFAULT FALSE;
ALTER TABLE "ShipmentStatusHistories" ADD COLUMN IF NOT EXISTS "DeviceInfo" VARCHAR(200);
ALTER TABLE "ShipmentStatusHistories" ADD COLUMN IF NOT EXISTS "Latitude" DECIMAL(18,8);
ALTER TABLE "ShipmentStatusHistories" ADD COLUMN IF NOT EXISTS "Longitude" DECIMAL(18,8);
ALTER TABLE "ShipmentStatusHistories" ADD COLUMN IF NOT EXISTS "IsActive" BOOLEAN DEFAULT TRUE;
ALTER TABLE "ShipmentStatusHistories" ADD COLUMN IF NOT EXISTS "IsDeleted" BOOLEAN DEFAULT FALSE;
ALTER TABLE "ShipmentStatusHistories" ADD COLUMN IF NOT EXISTS "IsDemo" BOOLEAN DEFAULT FALSE;
ALTER TABLE "ShipmentStatusHistories" ADD COLUMN IF NOT EXISTS "CreatedAt" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "ShipmentStatusHistories" ADD COLUMN IF NOT EXISTS "ModifiedAt" TIMESTAMP WITH TIME ZONE;
ALTER TABLE "ShipmentStatusHistories" ADD COLUMN IF NOT EXISTS "CreatedBy" INT;
ALTER TABLE "ShipmentStatusHistories" ADD COLUMN IF NOT EXISTS "ModifiedBy" INT;

-- ============================================
-- ShipmentStatuses
-- ============================================
ALTER TABLE "ShipmentStatuses" ADD COLUMN IF NOT EXISTS "Code" VARCHAR(50);
ALTER TABLE "ShipmentStatuses" ADD COLUMN IF NOT EXISTS "Name" VARCHAR(200);
ALTER TABLE "ShipmentStatuses" ADD COLUMN IF NOT EXISTS "StatusGroupId" BIGINT;
ALTER TABLE "ShipmentStatuses" ADD COLUMN IF NOT EXISTS "TimelineDescription" VARCHAR(500);
ALTER TABLE "ShipmentStatuses" ADD COLUMN IF NOT EXISTS "ColorCode" VARCHAR(20);
ALTER TABLE "ShipmentStatuses" ADD COLUMN IF NOT EXISTS "IconName" VARCHAR(100);
ALTER TABLE "ShipmentStatuses" ADD COLUMN IF NOT EXISTS "SequenceNo" INT DEFAULT 0;
ALTER TABLE "ShipmentStatuses" ADD COLUMN IF NOT EXISTS "IsTerminal" BOOLEAN DEFAULT FALSE;
ALTER TABLE "ShipmentStatuses" ADD COLUMN IF NOT EXISTS "IsException" BOOLEAN DEFAULT FALSE;
ALTER TABLE "ShipmentStatuses" ADD COLUMN IF NOT EXISTS "MapsToCourierStatus" INT;
ALTER TABLE "ShipmentStatuses" ADD COLUMN IF NOT EXISTS "RequiresPOD" BOOLEAN DEFAULT FALSE;
ALTER TABLE "ShipmentStatuses" ADD COLUMN IF NOT EXISTS "RequiresLocation" BOOLEAN DEFAULT FALSE;
ALTER TABLE "ShipmentStatuses" ADD COLUMN IF NOT EXISTS "RequiresRemarks" BOOLEAN DEFAULT FALSE;
ALTER TABLE "ShipmentStatuses" ADD COLUMN IF NOT EXISTS "IsActive" BOOLEAN DEFAULT TRUE;
ALTER TABLE "ShipmentStatuses" ADD COLUMN IF NOT EXISTS "IsDeleted" BOOLEAN DEFAULT FALSE;
ALTER TABLE "ShipmentStatuses" ADD COLUMN IF NOT EXISTS "IsDemo" BOOLEAN DEFAULT FALSE;
ALTER TABLE "ShipmentStatuses" ADD COLUMN IF NOT EXISTS "CreatedAt" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "ShipmentStatuses" ADD COLUMN IF NOT EXISTS "ModifiedAt" TIMESTAMP WITH TIME ZONE;
ALTER TABLE "ShipmentStatuses" ADD COLUMN IF NOT EXISTS "CreatedBy" INT;
ALTER TABLE "ShipmentStatuses" ADD COLUMN IF NOT EXISTS "ModifiedBy" INT;

-- ============================================
-- ShipmentStatusGroups
-- ============================================
ALTER TABLE "ShipmentStatusGroups" ADD COLUMN IF NOT EXISTS "Code" VARCHAR(50);
ALTER TABLE "ShipmentStatusGroups" ADD COLUMN IF NOT EXISTS "Name" VARCHAR(200);
ALTER TABLE "ShipmentStatusGroups" ADD COLUMN IF NOT EXISTS "Description" VARCHAR(500);
ALTER TABLE "ShipmentStatusGroups" ADD COLUMN IF NOT EXISTS "ColorCode" VARCHAR(20);
ALTER TABLE "ShipmentStatusGroups" ADD COLUMN IF NOT EXISTS "IconName" VARCHAR(100);
ALTER TABLE "ShipmentStatusGroups" ADD COLUMN IF NOT EXISTS "SequenceNo" INT;
ALTER TABLE "ShipmentStatusGroups" ADD COLUMN IF NOT EXISTS "IsActive" BOOLEAN DEFAULT TRUE;
ALTER TABLE "ShipmentStatusGroups" ADD COLUMN IF NOT EXISTS "IsDeleted" BOOLEAN DEFAULT FALSE;
ALTER TABLE "ShipmentStatusGroups" ADD COLUMN IF NOT EXISTS "IsDemo" BOOLEAN DEFAULT FALSE;
ALTER TABLE "ShipmentStatusGroups" ADD COLUMN IF NOT EXISTS "CreatedAt" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "ShipmentStatusGroups" ADD COLUMN IF NOT EXISTS "ModifiedAt" TIMESTAMP WITH TIME ZONE;
ALTER TABLE "ShipmentStatusGroups" ADD COLUMN IF NOT EXISTS "CreatedBy" INT;
ALTER TABLE "ShipmentStatusGroups" ADD COLUMN IF NOT EXISTS "ModifiedBy" INT;

-- ============================================
-- ShipmentModes
-- ============================================
ALTER TABLE "ShipmentModes" ADD COLUMN IF NOT EXISTS "Code" VARCHAR(50);
ALTER TABLE "ShipmentModes" ADD COLUMN IF NOT EXISTS "Name" VARCHAR(200);
ALTER TABLE "ShipmentModes" ADD COLUMN IF NOT EXISTS "Description" VARCHAR(500);
ALTER TABLE "ShipmentModes" ADD COLUMN IF NOT EXISTS "TransitDays" INT;
ALTER TABLE "ShipmentModes" ADD COLUMN IF NOT EXISTS "IsExpress" BOOLEAN DEFAULT FALSE;
ALTER TABLE "ShipmentModes" ADD COLUMN IF NOT EXISTS "IsActive" BOOLEAN DEFAULT TRUE;
ALTER TABLE "ShipmentModes" ADD COLUMN IF NOT EXISTS "IsDeleted" BOOLEAN DEFAULT FALSE;
ALTER TABLE "ShipmentModes" ADD COLUMN IF NOT EXISTS "IsDemo" BOOLEAN DEFAULT FALSE;
ALTER TABLE "ShipmentModes" ADD COLUMN IF NOT EXISTS "CreatedAt" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "ShipmentModes" ADD COLUMN IF NOT EXISTS "ModifiedAt" TIMESTAMP WITH TIME ZONE;
ALTER TABLE "ShipmentModes" ADD COLUMN IF NOT EXISTS "CreatedBy" INT;
ALTER TABLE "ShipmentModes" ADD COLUMN IF NOT EXISTS "ModifiedBy" INT;

-- ============================================
-- ImportShipments
-- ============================================
ALTER TABLE "ImportShipments" ADD COLUMN IF NOT EXISTS "ImportMasterId" BIGINT;
ALTER TABLE "ImportShipments" ADD COLUMN IF NOT EXISTS "ImportBagId" BIGINT;
ALTER TABLE "ImportShipments" ADD COLUMN IF NOT EXISTS "AWBNo" VARCHAR(50);
ALTER TABLE "ImportShipments" ADD COLUMN IF NOT EXISTS "ReferenceNo" VARCHAR(100);
ALTER TABLE "ImportShipments" ADD COLUMN IF NOT EXISTS "ShipperName" VARCHAR(200);
ALTER TABLE "ImportShipments" ADD COLUMN IF NOT EXISTS "ShipperAddress" VARCHAR(500);
ALTER TABLE "ImportShipments" ADD COLUMN IF NOT EXISTS "ShipperCity" VARCHAR(100);
ALTER TABLE "ImportShipments" ADD COLUMN IF NOT EXISTS "ShipperCountry" VARCHAR(100);
ALTER TABLE "ImportShipments" ADD COLUMN IF NOT EXISTS "ShipperPhone" VARCHAR(50);
ALTER TABLE "ImportShipments" ADD COLUMN IF NOT EXISTS "ConsigneeName" VARCHAR(200);
ALTER TABLE "ImportShipments" ADD COLUMN IF NOT EXISTS "ConsigneeAddress" VARCHAR(500);
ALTER TABLE "ImportShipments" ADD COLUMN IF NOT EXISTS "ConsigneeCity" VARCHAR(100);
ALTER TABLE "ImportShipments" ADD COLUMN IF NOT EXISTS "ConsigneeState" VARCHAR(100);
ALTER TABLE "ImportShipments" ADD COLUMN IF NOT EXISTS "ConsigneeCountry" VARCHAR(100);
ALTER TABLE "ImportShipments" ADD COLUMN IF NOT EXISTS "ConsigneePostalCode" VARCHAR(20);
ALTER TABLE "ImportShipments" ADD COLUMN IF NOT EXISTS "ConsigneePhone" VARCHAR(50);
ALTER TABLE "ImportShipments" ADD COLUMN IF NOT EXISTS "ConsigneeMobile" VARCHAR(50);
ALTER TABLE "ImportShipments" ADD COLUMN IF NOT EXISTS "Pieces" INT DEFAULT 1;
ALTER TABLE "ImportShipments" ADD COLUMN IF NOT EXISTS "Weight" DECIMAL(18,3);
ALTER TABLE "ImportShipments" ADD COLUMN IF NOT EXISTS "VolumetricWeight" DECIMAL(18,3);
ALTER TABLE "ImportShipments" ADD COLUMN IF NOT EXISTS "ChargeableWeight" DECIMAL(18,3);
ALTER TABLE "ImportShipments" ADD COLUMN IF NOT EXISTS "ShipmentType" INT DEFAULT 1;
ALTER TABLE "ImportShipments" ADD COLUMN IF NOT EXISTS "ImportType" INT DEFAULT 0;
ALTER TABLE "ImportShipments" ADD COLUMN IF NOT EXISTS "PaymentMode" INT DEFAULT 0;
ALTER TABLE "ImportShipments" ADD COLUMN IF NOT EXISTS "ContentsDescription" VARCHAR(500);
ALTER TABLE "ImportShipments" ADD COLUMN IF NOT EXISTS "SpecialInstructions" VARCHAR(500);
ALTER TABLE "ImportShipments" ADD COLUMN IF NOT EXISTS "DeclaredValue" DECIMAL(18,2);
ALTER TABLE "ImportShipments" ADD COLUMN IF NOT EXISTS "Currency" VARCHAR(10);
ALTER TABLE "ImportShipments" ADD COLUMN IF NOT EXISTS "HSCode" VARCHAR(50);
ALTER TABLE "ImportShipments" ADD COLUMN IF NOT EXISTS "DutyAmount" DECIMAL(18,2);
ALTER TABLE "ImportShipments" ADD COLUMN IF NOT EXISTS "VATAmount" DECIMAL(18,2);
ALTER TABLE "ImportShipments" ADD COLUMN IF NOT EXISTS "OtherCharges" DECIMAL(18,2);
ALTER TABLE "ImportShipments" ADD COLUMN IF NOT EXISTS "TotalCustomsCharges" DECIMAL(18,2);
ALTER TABLE "ImportShipments" ADD COLUMN IF NOT EXISTS "IsCOD" BOOLEAN DEFAULT FALSE;
ALTER TABLE "ImportShipments" ADD COLUMN IF NOT EXISTS "CODAmount" DECIMAL(18,2);
ALTER TABLE "ImportShipments" ADD COLUMN IF NOT EXISTS "Status" INT DEFAULT 0;
ALTER TABLE "ImportShipments" ADD COLUMN IF NOT EXISTS "CustomsStatus" INT DEFAULT 0;
ALTER TABLE "ImportShipments" ADD COLUMN IF NOT EXISTS "CustomsWorkStatus" INT;
ALTER TABLE "ImportShipments" ADD COLUMN IF NOT EXISTS "HoldReason" INT DEFAULT 0;
ALTER TABLE "ImportShipments" ADD COLUMN IF NOT EXISTS "HoldReasonDetails" VARCHAR(500);
ALTER TABLE "ImportShipments" ADD COLUMN IF NOT EXISTS "ImporterOfRecord" VARCHAR(200);
ALTER TABLE "ImportShipments" ADD COLUMN IF NOT EXISTS "CustomsEntryNumber" VARCHAR(100);
ALTER TABLE "ImportShipments" ADD COLUMN IF NOT EXISTS "ExaminationRemarks" VARCHAR(500);
ALTER TABLE "ImportShipments" ADD COLUMN IF NOT EXISTS "InscannedAt" TIMESTAMP WITH TIME ZONE;
ALTER TABLE "ImportShipments" ADD COLUMN IF NOT EXISTS "InscannedByUserId" BIGINT;
ALTER TABLE "ImportShipments" ADD COLUMN IF NOT EXISTS "InscannedByUserName" VARCHAR(200);
ALTER TABLE "ImportShipments" ADD COLUMN IF NOT EXISTS "CustomsClearedAt" TIMESTAMP WITH TIME ZONE;
ALTER TABLE "ImportShipments" ADD COLUMN IF NOT EXISTS "CustomsClearedByUserId" BIGINT;
ALTER TABLE "ImportShipments" ADD COLUMN IF NOT EXISTS "CustomsClearedByUserName" VARCHAR(200);
ALTER TABLE "ImportShipments" ADD COLUMN IF NOT EXISTS "ReleasedAt" TIMESTAMP WITH TIME ZONE;
ALTER TABLE "ImportShipments" ADD COLUMN IF NOT EXISTS "ReleasedByUserId" BIGINT;
ALTER TABLE "ImportShipments" ADD COLUMN IF NOT EXISTS "ReleasedByUserName" VARCHAR(200);
ALTER TABLE "ImportShipments" ADD COLUMN IF NOT EXISTS "HandedOverAt" TIMESTAMP WITH TIME ZONE;
ALTER TABLE "ImportShipments" ADD COLUMN IF NOT EXISTS "HandedOverToUserId" BIGINT;
ALTER TABLE "ImportShipments" ADD COLUMN IF NOT EXISTS "HandedOverToUserName" VARCHAR(200);
ALTER TABLE "ImportShipments" ADD COLUMN IF NOT EXISTS "LinkedInscanMasterId" BIGINT;
ALTER TABLE "ImportShipments" ADD COLUMN IF NOT EXISTS "Remarks" VARCHAR(500);
ALTER TABLE "ImportShipments" ADD COLUMN IF NOT EXISTS "DutyVatAmount" DECIMAL(18,2);
ALTER TABLE "ImportShipments" ADD COLUMN IF NOT EXISTS "CalculatedImportVAT" DECIMAL(18,2);
ALTER TABLE "ImportShipments" ADD COLUMN IF NOT EXISTS "NetTotal" DECIMAL(18,2);
ALTER TABLE "ImportShipments" ADD COLUMN IF NOT EXISTS "CustomsValue" DECIMAL(18,2);
ALTER TABLE "ImportShipments" ADD COLUMN IF NOT EXISTS "IsActive" BOOLEAN DEFAULT TRUE;
ALTER TABLE "ImportShipments" ADD COLUMN IF NOT EXISTS "IsDeleted" BOOLEAN DEFAULT FALSE;
ALTER TABLE "ImportShipments" ADD COLUMN IF NOT EXISTS "IsDemo" BOOLEAN DEFAULT FALSE;
ALTER TABLE "ImportShipments" ADD COLUMN IF NOT EXISTS "CreatedAt" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "ImportShipments" ADD COLUMN IF NOT EXISTS "ModifiedAt" TIMESTAMP WITH TIME ZONE;
ALTER TABLE "ImportShipments" ADD COLUMN IF NOT EXISTS "CreatedBy" INT;
ALTER TABLE "ImportShipments" ADD COLUMN IF NOT EXISTS "ModifiedBy" INT;
ALTER TABLE "ImportShipments" ADD COLUMN IF NOT EXISTS "CreatedByName" VARCHAR(200);
ALTER TABLE "ImportShipments" ADD COLUMN IF NOT EXISTS "ModifiedByName" VARCHAR(200);

-- ============================================
-- ImportMasters
-- ============================================
ALTER TABLE "ImportMasters" ADD COLUMN IF NOT EXISTS "ImportRefNo" VARCHAR(50);
ALTER TABLE "ImportMasters" ADD COLUMN IF NOT EXISTS "TransactionDate" TIMESTAMP WITH TIME ZONE;
ALTER TABLE "ImportMasters" ADD COLUMN IF NOT EXISTS "CompanyId" BIGINT;
ALTER TABLE "ImportMasters" ADD COLUMN IF NOT EXISTS "BranchId" BIGINT;
ALTER TABLE "ImportMasters" ADD COLUMN IF NOT EXISTS "FinancialYearId" BIGINT;
ALTER TABLE "ImportMasters" ADD COLUMN IF NOT EXISTS "MAWBNo" VARCHAR(50);
ALTER TABLE "ImportMasters" ADD COLUMN IF NOT EXISTS "FlightNo" VARCHAR(50);
ALTER TABLE "ImportMasters" ADD COLUMN IF NOT EXISTS "FlightDate" TIMESTAMP WITH TIME ZONE;
ALTER TABLE "ImportMasters" ADD COLUMN IF NOT EXISTS "OriginAirportCode" VARCHAR(10);
ALTER TABLE "ImportMasters" ADD COLUMN IF NOT EXISTS "DestinationAirportCode" VARCHAR(10);
ALTER TABLE "ImportMasters" ADD COLUMN IF NOT EXISTS "CarrierId" BIGINT;
ALTER TABLE "ImportMasters" ADD COLUMN IF NOT EXISTS "CarrierName" VARCHAR(200);
ALTER TABLE "ImportMasters" ADD COLUMN IF NOT EXISTS "AgentId" BIGINT;
ALTER TABLE "ImportMasters" ADD COLUMN IF NOT EXISTS "AgentName" VARCHAR(200);
ALTER TABLE "ImportMasters" ADD COLUMN IF NOT EXISTS "TotalPieces" INT;
ALTER TABLE "ImportMasters" ADD COLUMN IF NOT EXISTS "TotalWeight" DECIMAL(18,3);
ALTER TABLE "ImportMasters" ADD COLUMN IF NOT EXISTS "TotalShipments" INT;
ALTER TABLE "ImportMasters" ADD COLUMN IF NOT EXISTS "Status" INT DEFAULT 0;
ALTER TABLE "ImportMasters" ADD COLUMN IF NOT EXISTS "ReceivedAt" TIMESTAMP WITH TIME ZONE;
ALTER TABLE "ImportMasters" ADD COLUMN IF NOT EXISTS "ReceivedByUserId" BIGINT;
ALTER TABLE "ImportMasters" ADD COLUMN IF NOT EXISTS "ReceivedByUserName" VARCHAR(200);
ALTER TABLE "ImportMasters" ADD COLUMN IF NOT EXISTS "Remarks" VARCHAR(500);
ALTER TABLE "ImportMasters" ADD COLUMN IF NOT EXISTS "IsActive" BOOLEAN DEFAULT TRUE;
ALTER TABLE "ImportMasters" ADD COLUMN IF NOT EXISTS "IsDeleted" BOOLEAN DEFAULT FALSE;
ALTER TABLE "ImportMasters" ADD COLUMN IF NOT EXISTS "IsDemo" BOOLEAN DEFAULT FALSE;
ALTER TABLE "ImportMasters" ADD COLUMN IF NOT EXISTS "CreatedAt" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "ImportMasters" ADD COLUMN IF NOT EXISTS "ModifiedAt" TIMESTAMP WITH TIME ZONE;
ALTER TABLE "ImportMasters" ADD COLUMN IF NOT EXISTS "CreatedBy" INT;
ALTER TABLE "ImportMasters" ADD COLUMN IF NOT EXISTS "ModifiedBy" INT;
ALTER TABLE "ImportMasters" ADD COLUMN IF NOT EXISTS "CreatedByName" VARCHAR(200);
ALTER TABLE "ImportMasters" ADD COLUMN IF NOT EXISTS "ModifiedByName" VARCHAR(200);

-- ============================================
-- DRS (Delivery Run Sheet)
-- ============================================
ALTER TABLE "DRS" ADD COLUMN IF NOT EXISTS "DRSNo" VARCHAR(50);
ALTER TABLE "DRS" ADD COLUMN IF NOT EXISTS "TransactionDate" TIMESTAMP WITH TIME ZONE;
ALTER TABLE "DRS" ADD COLUMN IF NOT EXISTS "CompanyId" BIGINT;
ALTER TABLE "DRS" ADD COLUMN IF NOT EXISTS "BranchId" BIGINT;
ALTER TABLE "DRS" ADD COLUMN IF NOT EXISTS "FinancialYearId" BIGINT;
ALTER TABLE "DRS" ADD COLUMN IF NOT EXISTS "EmployeeId" BIGINT;
ALTER TABLE "DRS" ADD COLUMN IF NOT EXISTS "EmployeeName" VARCHAR(200);
ALTER TABLE "DRS" ADD COLUMN IF NOT EXISTS "VehicleId" BIGINT;
ALTER TABLE "DRS" ADD COLUMN IF NOT EXISTS "VehicleNo" VARCHAR(50);
ALTER TABLE "DRS" ADD COLUMN IF NOT EXISTS "TotalShipments" INT;
ALTER TABLE "DRS" ADD COLUMN IF NOT EXISTS "TotalWeight" DECIMAL(18,3);
ALTER TABLE "DRS" ADD COLUMN IF NOT EXISTS "TotalCOD" DECIMAL(18,2);
ALTER TABLE "DRS" ADD COLUMN IF NOT EXISTS "Status" INT DEFAULT 0;
ALTER TABLE "DRS" ADD COLUMN IF NOT EXISTS "DispatchedAt" TIMESTAMP WITH TIME ZONE;
ALTER TABLE "DRS" ADD COLUMN IF NOT EXISTS "DispatchedByUserId" BIGINT;
ALTER TABLE "DRS" ADD COLUMN IF NOT EXISTS "DispatchedByUserName" VARCHAR(200);
ALTER TABLE "DRS" ADD COLUMN IF NOT EXISTS "ClosedAt" TIMESTAMP WITH TIME ZONE;
ALTER TABLE "DRS" ADD COLUMN IF NOT EXISTS "ClosedByUserId" BIGINT;
ALTER TABLE "DRS" ADD COLUMN IF NOT EXISTS "ClosedByUserName" VARCHAR(200);
ALTER TABLE "DRS" ADD COLUMN IF NOT EXISTS "Remarks" VARCHAR(500);
ALTER TABLE "DRS" ADD COLUMN IF NOT EXISTS "IsActive" BOOLEAN DEFAULT TRUE;
ALTER TABLE "DRS" ADD COLUMN IF NOT EXISTS "IsDeleted" BOOLEAN DEFAULT FALSE;
ALTER TABLE "DRS" ADD COLUMN IF NOT EXISTS "IsDemo" BOOLEAN DEFAULT FALSE;
ALTER TABLE "DRS" ADD COLUMN IF NOT EXISTS "CreatedAt" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "DRS" ADD COLUMN IF NOT EXISTS "ModifiedAt" TIMESTAMP WITH TIME ZONE;
ALTER TABLE "DRS" ADD COLUMN IF NOT EXISTS "CreatedBy" INT;
ALTER TABLE "DRS" ADD COLUMN IF NOT EXISTS "ModifiedBy" INT;
ALTER TABLE "DRS" ADD COLUMN IF NOT EXISTS "CreatedByName" VARCHAR(200);
ALTER TABLE "DRS" ADD COLUMN IF NOT EXISTS "ModifiedByName" VARCHAR(200);

-- ============================================
-- DRSReconciliationStatements
-- ============================================
ALTER TABLE "DRSReconciliationStatements" ADD COLUMN IF NOT EXISTS "DRSId" BIGINT;
ALTER TABLE "DRSReconciliationStatements" ADD COLUMN IF NOT EXISTS "ReceiptId" BIGINT;
ALTER TABLE "DRSReconciliationStatements" ADD COLUMN IF NOT EXISTS "StatementNo" VARCHAR(50);
ALTER TABLE "DRSReconciliationStatements" ADD COLUMN IF NOT EXISTS "TransactionDate" TIMESTAMP WITH TIME ZONE;
ALTER TABLE "DRSReconciliationStatements" ADD COLUMN IF NOT EXISTS "CompanyId" BIGINT;
ALTER TABLE "DRSReconciliationStatements" ADD COLUMN IF NOT EXISTS "BranchId" BIGINT;
ALTER TABLE "DRSReconciliationStatements" ADD COLUMN IF NOT EXISTS "CourierId" BIGINT;
ALTER TABLE "DRSReconciliationStatements" ADD COLUMN IF NOT EXISTS "CourierName" VARCHAR(200);
ALTER TABLE "DRSReconciliationStatements" ADD COLUMN IF NOT EXISTS "TotalShipments" INT;
ALTER TABLE "DRSReconciliationStatements" ADD COLUMN IF NOT EXISTS "TotalMaterialCost" DECIMAL(18,2);
ALTER TABLE "DRSReconciliationStatements" ADD COLUMN IF NOT EXISTS "TotalCODAmount" DECIMAL(18,2);
ALTER TABLE "DRSReconciliationStatements" ADD COLUMN IF NOT EXISTS "TotalOtherCharges" DECIMAL(18,2);
ALTER TABLE "DRSReconciliationStatements" ADD COLUMN IF NOT EXISTS "TotalDiscount" DECIMAL(18,2);
ALTER TABLE "DRSReconciliationStatements" ADD COLUMN IF NOT EXISTS "TotalCollected" DECIMAL(18,2);
ALTER TABLE "DRSReconciliationStatements" ADD COLUMN IF NOT EXISTS "TotalExpenses" DECIMAL(18,2);
ALTER TABLE "DRSReconciliationStatements" ADD COLUMN IF NOT EXISTS "ReceiptAmount" DECIMAL(18,2);
ALTER TABLE "DRSReconciliationStatements" ADD COLUMN IF NOT EXISTS "Variance" DECIMAL(18,2);
ALTER TABLE "DRSReconciliationStatements" ADD COLUMN IF NOT EXISTS "Status" INT DEFAULT 0;
ALTER TABLE "DRSReconciliationStatements" ADD COLUMN IF NOT EXISTS "Remarks" VARCHAR(500);
ALTER TABLE "DRSReconciliationStatements" ADD COLUMN IF NOT EXISTS "CompletedAt" TIMESTAMP WITH TIME ZONE;
ALTER TABLE "DRSReconciliationStatements" ADD COLUMN IF NOT EXISTS "CompletedByUserId" BIGINT;
ALTER TABLE "DRSReconciliationStatements" ADD COLUMN IF NOT EXISTS "CompletedByUserName" VARCHAR(200);
ALTER TABLE "DRSReconciliationStatements" ADD COLUMN IF NOT EXISTS "ApprovedAt" TIMESTAMP WITH TIME ZONE;
ALTER TABLE "DRSReconciliationStatements" ADD COLUMN IF NOT EXISTS "ApprovedByUserId" BIGINT;
ALTER TABLE "DRSReconciliationStatements" ADD COLUMN IF NOT EXISTS "ApprovedByUserName" VARCHAR(200);
ALTER TABLE "DRSReconciliationStatements" ADD COLUMN IF NOT EXISTS "IsActive" BOOLEAN DEFAULT TRUE;
ALTER TABLE "DRSReconciliationStatements" ADD COLUMN IF NOT EXISTS "IsDeleted" BOOLEAN DEFAULT FALSE;
ALTER TABLE "DRSReconciliationStatements" ADD COLUMN IF NOT EXISTS "IsDemo" BOOLEAN DEFAULT FALSE;
ALTER TABLE "DRSReconciliationStatements" ADD COLUMN IF NOT EXISTS "CreatedAt" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "DRSReconciliationStatements" ADD COLUMN IF NOT EXISTS "ModifiedAt" TIMESTAMP WITH TIME ZONE;
ALTER TABLE "DRSReconciliationStatements" ADD COLUMN IF NOT EXISTS "CreatedBy" INT;
ALTER TABLE "DRSReconciliationStatements" ADD COLUMN IF NOT EXISTS "ModifiedBy" INT;
ALTER TABLE "DRSReconciliationStatements" ADD COLUMN IF NOT EXISTS "CreatedByName" VARCHAR(200);
ALTER TABLE "DRSReconciliationStatements" ADD COLUMN IF NOT EXISTS "ModifiedByName" VARCHAR(200);

-- ============================================
-- DRSReconciliationLines
-- ============================================
ALTER TABLE "DRSReconciliationLines" ADD COLUMN IF NOT EXISTS "DRSReconciliationStatementId" BIGINT;
ALTER TABLE "DRSReconciliationLines" ADD COLUMN IF NOT EXISTS "InscanMasterId" BIGINT;
ALTER TABLE "DRSReconciliationLines" ADD COLUMN IF NOT EXISTS "AWBNo" VARCHAR(50);
ALTER TABLE "DRSReconciliationLines" ADD COLUMN IF NOT EXISTS "MaterialCost" DECIMAL(18,2);
ALTER TABLE "DRSReconciliationLines" ADD COLUMN IF NOT EXISTS "CODAmount" DECIMAL(18,2);
ALTER TABLE "DRSReconciliationLines" ADD COLUMN IF NOT EXISTS "OtherCharges" DECIMAL(18,2);
ALTER TABLE "DRSReconciliationLines" ADD COLUMN IF NOT EXISTS "TotalAmount" DECIMAL(18,2);
ALTER TABLE "DRSReconciliationLines" ADD COLUMN IF NOT EXISTS "Discount" DECIMAL(18,2);
ALTER TABLE "DRSReconciliationLines" ADD COLUMN IF NOT EXISTS "NetAmount" DECIMAL(18,2);
ALTER TABLE "DRSReconciliationLines" ADD COLUMN IF NOT EXISTS "Remarks" VARCHAR(500);
ALTER TABLE "DRSReconciliationLines" ADD COLUMN IF NOT EXISTS "IsActive" BOOLEAN DEFAULT TRUE;
ALTER TABLE "DRSReconciliationLines" ADD COLUMN IF NOT EXISTS "IsDeleted" BOOLEAN DEFAULT FALSE;
ALTER TABLE "DRSReconciliationLines" ADD COLUMN IF NOT EXISTS "IsDemo" BOOLEAN DEFAULT FALSE;
ALTER TABLE "DRSReconciliationLines" ADD COLUMN IF NOT EXISTS "CreatedAt" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "DRSReconciliationLines" ADD COLUMN IF NOT EXISTS "ModifiedAt" TIMESTAMP WITH TIME ZONE;
ALTER TABLE "DRSReconciliationLines" ADD COLUMN IF NOT EXISTS "CreatedBy" INT;
ALTER TABLE "DRSReconciliationLines" ADD COLUMN IF NOT EXISTS "ModifiedBy" INT;

-- ============================================
-- Manifests
-- ============================================
ALTER TABLE "Manifests" ADD COLUMN IF NOT EXISTS "ManifestNo" VARCHAR(50);
ALTER TABLE "Manifests" ADD COLUMN IF NOT EXISTS "TransactionDate" TIMESTAMP WITH TIME ZONE;
ALTER TABLE "Manifests" ADD COLUMN IF NOT EXISTS "CompanyId" BIGINT;
ALTER TABLE "Manifests" ADD COLUMN IF NOT EXISTS "BranchId" BIGINT;
ALTER TABLE "Manifests" ADD COLUMN IF NOT EXISTS "FinancialYearId" BIGINT;
ALTER TABLE "Manifests" ADD COLUMN IF NOT EXISTS "OriginBranchId" BIGINT;
ALTER TABLE "Manifests" ADD COLUMN IF NOT EXISTS "DestinationBranchId" BIGINT;
ALTER TABLE "Manifests" ADD COLUMN IF NOT EXISTS "OriginBranchName" VARCHAR(200);
ALTER TABLE "Manifests" ADD COLUMN IF NOT EXISTS "DestinationBranchName" VARCHAR(200);
ALTER TABLE "Manifests" ADD COLUMN IF NOT EXISTS "VehicleId" BIGINT;
ALTER TABLE "Manifests" ADD COLUMN IF NOT EXISTS "VehicleNo" VARCHAR(50);
ALTER TABLE "Manifests" ADD COLUMN IF NOT EXISTS "DriverName" VARCHAR(200);
ALTER TABLE "Manifests" ADD COLUMN IF NOT EXISTS "DriverPhone" VARCHAR(50);
ALTER TABLE "Manifests" ADD COLUMN IF NOT EXISTS "TotalShipments" INT;
ALTER TABLE "Manifests" ADD COLUMN IF NOT EXISTS "TotalPieces" INT;
ALTER TABLE "Manifests" ADD COLUMN IF NOT EXISTS "TotalWeight" DECIMAL(18,3);
ALTER TABLE "Manifests" ADD COLUMN IF NOT EXISTS "Status" INT DEFAULT 0;
ALTER TABLE "Manifests" ADD COLUMN IF NOT EXISTS "DispatchedAt" TIMESTAMP WITH TIME ZONE;
ALTER TABLE "Manifests" ADD COLUMN IF NOT EXISTS "DispatchedByUserId" BIGINT;
ALTER TABLE "Manifests" ADD COLUMN IF NOT EXISTS "DispatchedByUserName" VARCHAR(200);
ALTER TABLE "Manifests" ADD COLUMN IF NOT EXISTS "ReceivedAt" TIMESTAMP WITH TIME ZONE;
ALTER TABLE "Manifests" ADD COLUMN IF NOT EXISTS "ReceivedByUserId" BIGINT;
ALTER TABLE "Manifests" ADD COLUMN IF NOT EXISTS "ReceivedByUserName" VARCHAR(200);
ALTER TABLE "Manifests" ADD COLUMN IF NOT EXISTS "Remarks" VARCHAR(500);
ALTER TABLE "Manifests" ADD COLUMN IF NOT EXISTS "IsActive" BOOLEAN DEFAULT TRUE;
ALTER TABLE "Manifests" ADD COLUMN IF NOT EXISTS "IsDeleted" BOOLEAN DEFAULT FALSE;
ALTER TABLE "Manifests" ADD COLUMN IF NOT EXISTS "IsDemo" BOOLEAN DEFAULT FALSE;
ALTER TABLE "Manifests" ADD COLUMN IF NOT EXISTS "CreatedAt" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "Manifests" ADD COLUMN IF NOT EXISTS "ModifiedAt" TIMESTAMP WITH TIME ZONE;
ALTER TABLE "Manifests" ADD COLUMN IF NOT EXISTS "CreatedBy" INT;
ALTER TABLE "Manifests" ADD COLUMN IF NOT EXISTS "ModifiedBy" INT;
ALTER TABLE "Manifests" ADD COLUMN IF NOT EXISTS "CreatedByName" VARCHAR(200);
ALTER TABLE "Manifests" ADD COLUMN IF NOT EXISTS "ModifiedByName" VARCHAR(200);

-- ============================================
-- Indexes (safe to run - uses IF NOT EXISTS)
-- ============================================
CREATE INDEX IF NOT EXISTS "IX_InscanMasters_AWBNo" ON "InscanMasters"("AWBNo");
CREATE INDEX IF NOT EXISTS "IX_InscanMasters_TransactionDate" ON "InscanMasters"("TransactionDate");
CREATE INDEX IF NOT EXISTS "IX_InscanMasters_CustomerId" ON "InscanMasters"("CustomerId");
CREATE INDEX IF NOT EXISTS "IX_InscanMasters_BranchId" ON "InscanMasters"("BranchId");
CREATE INDEX IF NOT EXISTS "IX_InscanMasters_CourierStatusId" ON "InscanMasters"("CourierStatusId");
CREATE INDEX IF NOT EXISTS "IX_InscanMasters_MovementTypeId" ON "InscanMasters"("MovementTypeId");
CREATE INDEX IF NOT EXISTS "IX_InscanMasters_DRSId" ON "InscanMasters"("DRSId");
CREATE INDEX IF NOT EXISTS "IX_InscanMasters_ManifestId" ON "InscanMasters"("ManifestId");
CREATE INDEX IF NOT EXISTS "IX_ShipmentStatusHistories_InscanMasterId" ON "ShipmentStatusHistories"("InscanMasterId");
CREATE INDEX IF NOT EXISTS "IX_ShipmentStatusHistories_StatusId" ON "ShipmentStatusHistories"("StatusId");
CREATE INDEX IF NOT EXISTS "IX_ImportShipments_AWBNo" ON "ImportShipments"("AWBNo");
CREATE INDEX IF NOT EXISTS "IX_ImportShipments_ImportMasterId" ON "ImportShipments"("ImportMasterId");

-- ============================================
-- Companies (Company Master Table)
-- ============================================
ALTER TABLE "Companies" ADD COLUMN IF NOT EXISTS "Name" VARCHAR(200);
ALTER TABLE "Companies" ADD COLUMN IF NOT EXISTS "Code" VARCHAR(50);
ALTER TABLE "Companies" ADD COLUMN IF NOT EXISTS "Address" TEXT;
ALTER TABLE "Companies" ADD COLUMN IF NOT EXISTS "PostalCode" VARCHAR(20);
ALTER TABLE "Companies" ADD COLUMN IF NOT EXISTS "Phone" VARCHAR(50);
ALTER TABLE "Companies" ADD COLUMN IF NOT EXISTS "Email" VARCHAR(200);
ALTER TABLE "Companies" ADD COLUMN IF NOT EXISTS "Website" VARCHAR(200);
ALTER TABLE "Companies" ADD COLUMN IF NOT EXISTS "TaxNumber" VARCHAR(100);
ALTER TABLE "Companies" ADD COLUMN IF NOT EXISTS "RegistrationNumber" VARCHAR(100);
ALTER TABLE "Companies" ADD COLUMN IF NOT EXISTS "Logo" TEXT;
ALTER TABLE "Companies" ADD COLUMN IF NOT EXISTS "ContactPerson" VARCHAR(200);
ALTER TABLE "Companies" ADD COLUMN IF NOT EXISTS "ContactPersonPhone" VARCHAR(50);
ALTER TABLE "Companies" ADD COLUMN IF NOT EXISTS "ContactPersonEmail" VARCHAR(200);
ALTER TABLE "Companies" ADD COLUMN IF NOT EXISTS "SubscriptionStartDate" TIMESTAMP WITH TIME ZONE;
ALTER TABLE "Companies" ADD COLUMN IF NOT EXISTS "SubscriptionEndDate" TIMESTAMP WITH TIME ZONE;
ALTER TABLE "Companies" ADD COLUMN IF NOT EXISTS "SubscriptionPlan" VARCHAR(100);
ALTER TABLE "Companies" ADD COLUMN IF NOT EXISTS "CountryId" BIGINT;
ALTER TABLE "Companies" ADD COLUMN IF NOT EXISTS "StateId" BIGINT;
ALTER TABLE "Companies" ADD COLUMN IF NOT EXISTS "CityId" BIGINT;
ALTER TABLE "Companies" ADD COLUMN IF NOT EXISTS "CurrencyId" BIGINT;
ALTER TABLE "Companies" ADD COLUMN IF NOT EXISTS "UseAwbStockManagement" BOOLEAN DEFAULT TRUE;
ALTER TABLE "Companies" ADD COLUMN IF NOT EXISTS "InvoiceTermsAndConditions" TEXT;
ALTER TABLE "Companies" ADD COLUMN IF NOT EXISTS "BankAccountTitle" VARCHAR(200);
ALTER TABLE "Companies" ADD COLUMN IF NOT EXISTS "BankAccountTitleArabic" VARCHAR(200);
ALTER TABLE "Companies" ADD COLUMN IF NOT EXISTS "BankAccountNumber" VARCHAR(100);
ALTER TABLE "Companies" ADD COLUMN IF NOT EXISTS "BankIBANNumber" VARCHAR(100);
ALTER TABLE "Companies" ADD COLUMN IF NOT EXISTS "BankAccountType" VARCHAR(50);
ALTER TABLE "Companies" ADD COLUMN IF NOT EXISTS "BankAccountTypeArabic" VARCHAR(100);
ALTER TABLE "Companies" ADD COLUMN IF NOT EXISTS "BankCurrency" VARCHAR(20);
ALTER TABLE "Companies" ADD COLUMN IF NOT EXISTS "BankSWIFTCode" VARCHAR(50);
ALTER TABLE "Companies" ADD COLUMN IF NOT EXISTS "BankName" VARCHAR(200);
ALTER TABLE "Companies" ADD COLUMN IF NOT EXISTS "BankNameArabic" VARCHAR(200);

-- Done! All columns should now be present.
SELECT 'Production schema sync completed successfully!' AS result;
