-- Net4Courier Full Schema Sync Script
-- Run section by section in Replit SQL Console
-- Part 1: CREATE TABLES (run first for new installations)
-- Part 2: ALTER TABLES (run for existing installations)

-- =============================================
-- PART 1: CREATE TABLES (for new tables only)
-- =============================================

-- StatusEventMappings
CREATE TABLE IF NOT EXISTS "StatusEventMappings" (
    "Id" BIGSERIAL PRIMARY KEY,
    "CompanyId" BIGINT,
    "BranchId" BIGINT,
    "EventCode" VARCHAR(50) NOT NULL,
    "EventName" VARCHAR(100),
    "StatusId" BIGINT NOT NULL,
    "IsActive" BOOLEAN DEFAULT TRUE,
    "CreatedAt" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "ModifiedAt" TIMESTAMP,
    "CreatedBy" VARCHAR(255),
    "ModifiedBy" VARCHAR(255),
    "IsDeleted" BOOLEAN DEFAULT FALSE,
    "IsDemo" BOOLEAN DEFAULT FALSE
);

-- UserFavorites
CREATE TABLE IF NOT EXISTS "UserFavorites" (
    "Id" BIGSERIAL PRIMARY KEY,
    "UserId" BIGINT NOT NULL,
    "MenuPath" VARCHAR(255) NOT NULL,
    "MenuTitle" VARCHAR(255),
    "MenuIcon" VARCHAR(100),
    "DisplayOrder" INT DEFAULT 0,
    "CreatedAt" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "ModifiedAt" TIMESTAMP,
    "CreatedBy" VARCHAR(255),
    "ModifiedBy" VARCHAR(255),
    "IsDeleted" BOOLEAN DEFAULT FALSE,
    "IsDemo" BOOLEAN DEFAULT FALSE
);

-- BranchAWBConfigs
CREATE TABLE IF NOT EXISTS "BranchAWBConfigs" (
    "Id" BIGSERIAL PRIMARY KEY,
    "BranchId" BIGINT NOT NULL,
    "MovementType" INT NOT NULL,
    "AWBPrefix" VARCHAR(20),
    "AWBStartingNumber" BIGINT DEFAULT 1,
    "AWBIncrement" INT DEFAULT 1,
    "AWBLastUsedNumber" BIGINT DEFAULT 0,
    "IsActive" BOOLEAN DEFAULT TRUE,
    "CreatedAt" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "ModifiedAt" TIMESTAMP,
    "CreatedBy" VARCHAR(255),
    "ModifiedBy" VARCHAR(255),
    "IsDeleted" BOOLEAN DEFAULT FALSE,
    "IsDemo" BOOLEAN DEFAULT FALSE
);

-- ZoneCategories
CREATE TABLE IF NOT EXISTS "ZoneCategories" (
    "Id" BIGSERIAL PRIMARY KEY,
    "CompanyId" BIGINT,
    "Name" VARCHAR(100) NOT NULL,
    "Code" VARCHAR(20),
    "Description" TEXT,
    "CategoryType" INT DEFAULT 0,
    "MovementType" INT DEFAULT 0,
    "ForwardingAgentId" BIGINT,
    "DeliveryAgentId" BIGINT,
    "SortOrder" INT DEFAULT 0,
    "AllowCrossBranchMovement" BOOLEAN DEFAULT TRUE,
    "IsActive" BOOLEAN DEFAULT TRUE,
    "CreatedAt" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "ModifiedAt" TIMESTAMP,
    "CreatedBy" VARCHAR(255),
    "ModifiedBy" VARCHAR(255),
    "CreatedByName" TEXT,
    "ModifiedByName" TEXT,
    "IsDeleted" BOOLEAN DEFAULT FALSE,
    "IsDemo" BOOLEAN DEFAULT FALSE
);

-- CustomerZones
CREATE TABLE IF NOT EXISTS "CustomerZones" (
    "Id" BIGSERIAL PRIMARY KEY,
    "CompanyId" BIGINT,
    "BranchId" BIGINT,
    "Name" VARCHAR(100) NOT NULL,
    "Code" VARCHAR(20),
    "Description" TEXT,
    "IsActive" BOOLEAN DEFAULT TRUE,
    "CreatedAt" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "ModifiedAt" TIMESTAMP,
    "CreatedBy" VARCHAR(255),
    "ModifiedBy" VARCHAR(255),
    "IsDeleted" BOOLEAN DEFAULT FALSE,
    "IsDemo" BOOLEAN DEFAULT FALSE
);

-- CustomerZoneCities
CREATE TABLE IF NOT EXISTS "CustomerZoneCities" (
    "Id" BIGSERIAL PRIMARY KEY,
    "CustomerZoneId" BIGINT NOT NULL,
    "CityId" BIGINT NOT NULL,
    "CreatedAt" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "ModifiedAt" TIMESTAMP,
    "CreatedBy" VARCHAR(255),
    "ModifiedBy" VARCHAR(255),
    "IsDeleted" BOOLEAN DEFAULT FALSE,
    "IsDemo" BOOLEAN DEFAULT FALSE
);

-- CustomerZoneCouriers
CREATE TABLE IF NOT EXISTS "CustomerZoneCouriers" (
    "Id" BIGSERIAL PRIMARY KEY,
    "CustomerZoneId" BIGINT NOT NULL,
    "CourierId" BIGINT NOT NULL,
    "CreatedAt" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "ModifiedAt" TIMESTAMP,
    "CreatedBy" VARCHAR(255),
    "ModifiedBy" VARCHAR(255),
    "IsDeleted" BOOLEAN DEFAULT FALSE,
    "IsDemo" BOOLEAN DEFAULT FALSE
);

-- ShipmentStatusGroups
CREATE TABLE IF NOT EXISTS "ShipmentStatusGroups" (
    "Id" BIGSERIAL PRIMARY KEY,
    "Name" VARCHAR(100) NOT NULL,
    "Code" VARCHAR(50),
    "Description" TEXT,
    "SequenceNo" INT DEFAULT 0,
    "IconName" VARCHAR(100),
    "ColorCode" VARCHAR(20),
    "IsActive" BOOLEAN DEFAULT TRUE,
    "CreatedAt" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "ModifiedAt" TIMESTAMP,
    "CreatedBy" VARCHAR(255),
    "ModifiedBy" VARCHAR(255),
    "IsDeleted" BOOLEAN DEFAULT FALSE,
    "IsDemo" BOOLEAN DEFAULT FALSE
);

-- GLAccountClassifications
CREATE TABLE IF NOT EXISTS "GLAccountClassifications" (
    "Id" BIGSERIAL PRIMARY KEY,
    "CompanyId" BIGINT,
    "Name" VARCHAR(100) NOT NULL,
    "Code" VARCHAR(20),
    "AccountType" VARCHAR(50),
    "ParentId" BIGINT,
    "Level" INT DEFAULT 0,
    "IsActive" BOOLEAN DEFAULT TRUE,
    "CreatedAt" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "ModifiedAt" TIMESTAMP,
    "CreatedBy" VARCHAR(255),
    "ModifiedBy" VARCHAR(255),
    "IsDeleted" BOOLEAN DEFAULT FALSE,
    "IsDemo" BOOLEAN DEFAULT FALSE
);

-- TaxCodes
CREATE TABLE IF NOT EXISTS "TaxCodes" (
    "Id" UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    "TenantId" UUID,
    "Code" VARCHAR(50),
    "Description" VARCHAR(255),
    "Rate" DECIMAL(10,4) DEFAULT 0,
    "TaxType" INT DEFAULT 0,
    "IsActive" BOOLEAN DEFAULT TRUE,
    "CreatedAt" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "ModifiedAt" TIMESTAMP,
    "UpdatedAt" TIMESTAMP,
    "CreatedBy" TEXT,
    "UpdatedBy" TEXT
);

-- TicketCategories
CREATE TABLE IF NOT EXISTS "TicketCategories" (
    "Id" BIGSERIAL PRIMARY KEY,
    "Name" VARCHAR(100) NOT NULL,
    "Code" VARCHAR(20),
    "Description" TEXT,
    "SortOrder" INT DEFAULT 0,
    "IsActive" BOOLEAN DEFAULT TRUE,
    "CreatedAt" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "ModifiedAt" TIMESTAMP,
    "CreatedBy" INT,
    "ModifiedBy" INT,
    "IsDeleted" BOOLEAN DEFAULT FALSE,
    "IsDemo" BOOLEAN DEFAULT FALSE
);

-- Tickets
CREATE TABLE IF NOT EXISTS "Tickets" (
    "Id" BIGSERIAL PRIMARY KEY,
    "TicketNo" TEXT,
    "Subject" TEXT,
    "Description" TEXT,
    "CategoryId" BIGINT,
    "CategoryName" TEXT,
    "PartyId" BIGINT,
    "PartyName" TEXT,
    "AWBId" BIGINT,
    "AWBNo" TEXT,
    "Status" INT DEFAULT 0,
    "Priority" INT DEFAULT 0,
    "AssignedToUserId" BIGINT,
    "AssignedToUserName" TEXT,
    "FirstResponseAt" TIMESTAMP,
    "ResolvedAt" TIMESTAMP,
    "ClosedAt" TIMESTAMP,
    "ResolutionNotes" TEXT,
    "CustomerRating" INT,
    "CustomerFeedback" TEXT,
    "BranchId" BIGINT,
    "BranchName" TEXT,
    "IsActive" BOOLEAN DEFAULT TRUE,
    "CreatedAt" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "ModifiedAt" TIMESTAMP,
    "CreatedBy" INT,
    "ModifiedBy" INT,
    "IsDeleted" BOOLEAN DEFAULT FALSE,
    "IsDemo" BOOLEAN DEFAULT FALSE
);

-- TicketComments
CREATE TABLE IF NOT EXISTS "TicketComments" (
    "Id" BIGSERIAL PRIMARY KEY,
    "TicketId" BIGINT NOT NULL,
    "Comment" TEXT,
    "IsInternal" BOOLEAN DEFAULT FALSE,
    "CreatedByUserId" BIGINT,
    "CreatedByUserName" TEXT,
    "IsActive" BOOLEAN DEFAULT TRUE,
    "CreatedAt" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "ModifiedAt" TIMESTAMP,
    "CreatedBy" INT,
    "ModifiedBy" INT,
    "IsDeleted" BOOLEAN DEFAULT FALSE,
    "IsDemo" BOOLEAN DEFAULT FALSE
);

-- FuelSurcharges
CREATE TABLE IF NOT EXISTS "FuelSurcharges" (
    "Id" BIGSERIAL PRIMARY KEY,
    "CompanyId" BIGINT,
    "Name" VARCHAR(100) NOT NULL,
    "Percentage" DECIMAL(10,4) DEFAULT 0,
    "EffectiveFrom" TIMESTAMP NOT NULL,
    "EffectiveTo" TIMESTAMP,
    "ApplyToDomestic" BOOLEAN DEFAULT TRUE,
    "ApplyToInternational" BOOLEAN DEFAULT TRUE,
    "Notes" TEXT,
    "IsActive" BOOLEAN DEFAULT TRUE,
    "CreatedAt" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "ModifiedAt" TIMESTAMP,
    "CreatedBy" INT,
    "ModifiedBy" INT,
    "IsDeleted" BOOLEAN DEFAULT FALSE,
    "IsDemo" BOOLEAN DEFAULT FALSE
);

-- DiscountContracts
CREATE TABLE IF NOT EXISTS "DiscountContracts" (
    "Id" BIGSERIAL PRIMARY KEY,
    "CompanyId" BIGINT,
    "Name" VARCHAR(100) NOT NULL,
    "Description" TEXT,
    "PartyId" BIGINT,
    "PartyName" TEXT,
    "DiscountPercentage" DECIMAL(10,4) DEFAULT 0,
    "MinimumAmount" DECIMAL(18,2),
    "MaximumDiscount" DECIMAL(18,2),
    "EffectiveFrom" TIMESTAMP NOT NULL,
    "EffectiveTo" TIMESTAMP,
    "ApplyToDomestic" BOOLEAN DEFAULT TRUE,
    "ApplyToInternational" BOOLEAN DEFAULT TRUE,
    "ServiceTypeId" BIGINT,
    "ServiceTypeName" TEXT,
    "Notes" TEXT,
    "IsActive" BOOLEAN DEFAULT TRUE,
    "CreatedAt" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "ModifiedAt" TIMESTAMP,
    "CreatedBy" INT,
    "ModifiedBy" INT,
    "IsDeleted" BOOLEAN DEFAULT FALSE,
    "IsDemo" BOOLEAN DEFAULT FALSE
);

-- VendorBills
CREATE TABLE IF NOT EXISTS "VendorBills" (
    "Id" BIGSERIAL PRIMARY KEY,
    "BillNo" VARCHAR(50) NOT NULL,
    "VendorBillNo" VARCHAR(100),
    "BillDate" TIMESTAMP NOT NULL,
    "DueDate" TIMESTAMP,
    "CompanyId" BIGINT,
    "BranchId" BIGINT,
    "BranchName" TEXT,
    "FinancialYearId" BIGINT,
    "SupplierId" BIGINT,
    "SupplierName" TEXT,
    "Description" TEXT,
    "SubTotal" DECIMAL(18,2) DEFAULT 0,
    "TaxPercent" DECIMAL(10,4),
    "TaxAmount" DECIMAL(18,2),
    "TotalAmount" DECIMAL(18,2) DEFAULT 0,
    "PaidAmount" DECIMAL(18,2) DEFAULT 0,
    "BalanceAmount" DECIMAL(18,2) DEFAULT 0,
    "CurrencyCode" VARCHAR(10),
    "Status" INT DEFAULT 1,
    "Remarks" TEXT,
    "JournalId" BIGINT,
    "ApprovedDate" TIMESTAMP,
    "ApprovedBy" TEXT,
    "IsActive" BOOLEAN DEFAULT TRUE,
    "CreatedAt" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "ModifiedAt" TIMESTAMP,
    "CreatedBy" INT,
    "ModifiedBy" INT,
    "IsDeleted" BOOLEAN DEFAULT FALSE,
    "IsDemo" BOOLEAN DEFAULT FALSE
);

-- =============================================
-- PART 2: ALTER TABLES (add missing columns)
-- =============================================

-- BRANCHES
ALTER TABLE "Branches" ADD COLUMN IF NOT EXISTS "TimeZoneId" VARCHAR(100) DEFAULT 'Asia/Dubai';
ALTER TABLE "Branches" ADD COLUMN IF NOT EXISTS "UseAwbStockManagement" BOOLEAN DEFAULT FALSE;
ALTER TABLE "Branches" ADD COLUMN IF NOT EXISTS "HideAccountCodes" BOOLEAN DEFAULT FALSE;
ALTER TABLE "Branches" ADD COLUMN IF NOT EXISTS "VatPercentage" DECIMAL(5,2) DEFAULT 5.00;
ALTER TABLE "Branches" ADD COLUMN IF NOT EXISTS "CurrencyId" BIGINT;
ALTER TABLE "Branches" ADD COLUMN IF NOT EXISTS "AWBPrefix" VARCHAR(20);
ALTER TABLE "Branches" ADD COLUMN IF NOT EXISTS "AWBStartingNumber" BIGINT DEFAULT 1;
ALTER TABLE "Branches" ADD COLUMN IF NOT EXISTS "AWBIncrement" INT DEFAULT 1;
ALTER TABLE "Branches" ADD COLUMN IF NOT EXISTS "AWBLastUsedNumber" BIGINT DEFAULT 0;
ALTER TABLE "Branches" ADD COLUMN IF NOT EXISTS "IsDemo" BOOLEAN DEFAULT FALSE;

-- COMPANIES
ALTER TABLE "Companies" ADD COLUMN IF NOT EXISTS "UseAwbStockManagement" BOOLEAN DEFAULT FALSE;
ALTER TABLE "Companies" ADD COLUMN IF NOT EXISTS "InvoiceTermsAndConditions" TEXT;
ALTER TABLE "Companies" ADD COLUMN IF NOT EXISTS "BankAccountTitle" VARCHAR(255);
ALTER TABLE "Companies" ADD COLUMN IF NOT EXISTS "BankAccountTitleArabic" VARCHAR(255);
ALTER TABLE "Companies" ADD COLUMN IF NOT EXISTS "BankAccountNumber" VARCHAR(100);
ALTER TABLE "Companies" ADD COLUMN IF NOT EXISTS "BankIBANNumber" VARCHAR(100);
ALTER TABLE "Companies" ADD COLUMN IF NOT EXISTS "BankAccountType" VARCHAR(50);
ALTER TABLE "Companies" ADD COLUMN IF NOT EXISTS "BankAccountTypeArabic" VARCHAR(100);
ALTER TABLE "Companies" ADD COLUMN IF NOT EXISTS "BankCurrency" VARCHAR(20);
ALTER TABLE "Companies" ADD COLUMN IF NOT EXISTS "BankSWIFTCode" VARCHAR(50);
ALTER TABLE "Companies" ADD COLUMN IF NOT EXISTS "BankName" VARCHAR(255);
ALTER TABLE "Companies" ADD COLUMN IF NOT EXISTS "BankNameArabic" VARCHAR(255);
ALTER TABLE "Companies" ADD COLUMN IF NOT EXISTS "IsDemo" BOOLEAN DEFAULT FALSE;

-- IMPORT MASTERS
ALTER TABLE "ImportMasters" ADD COLUMN IF NOT EXISTS "InscannedAt" TIMESTAMP;
ALTER TABLE "ImportMasters" ADD COLUMN IF NOT EXISTS "InscannedByUserId" BIGINT;
ALTER TABLE "ImportMasters" ADD COLUMN IF NOT EXISTS "InscannedByUserName" VARCHAR(255);
ALTER TABLE "ImportMasters" ADD COLUMN IF NOT EXISTS "ClosedAt" TIMESTAMP;
ALTER TABLE "ImportMasters" ADD COLUMN IF NOT EXISTS "ClosedByUserId" BIGINT;
ALTER TABLE "ImportMasters" ADD COLUMN IF NOT EXISTS "ClosedByUserName" VARCHAR(255);
ALTER TABLE "ImportMasters" ADD COLUMN IF NOT EXISTS "CreatedByName" VARCHAR(255);
ALTER TABLE "ImportMasters" ADD COLUMN IF NOT EXISTS "ModifiedByName" VARCHAR(255);
ALTER TABLE "ImportMasters" ADD COLUMN IF NOT EXISTS "IsDemo" BOOLEAN DEFAULT FALSE;

-- IMPORT SHIPMENTS
ALTER TABLE "ImportShipments" ADD COLUMN IF NOT EXISTS "InscannedAt" TIMESTAMP;
ALTER TABLE "ImportShipments" ADD COLUMN IF NOT EXISTS "InscannedByUserId" BIGINT;
ALTER TABLE "ImportShipments" ADD COLUMN IF NOT EXISTS "InscannedByUserName" VARCHAR(255);
ALTER TABLE "ImportShipments" ADD COLUMN IF NOT EXISTS "CustomsValue" DECIMAL(18,4) DEFAULT 0;
ALTER TABLE "ImportShipments" ADD COLUMN IF NOT EXISTS "DutyAmount" DECIMAL(18,4) DEFAULT 0;
ALTER TABLE "ImportShipments" ADD COLUMN IF NOT EXISTS "DutyVatAmount" DECIMAL(18,4) DEFAULT 0;
ALTER TABLE "ImportShipments" ADD COLUMN IF NOT EXISTS "CalculatedImportVAT" DECIMAL(18,4) DEFAULT 0;
ALTER TABLE "ImportShipments" ADD COLUMN IF NOT EXISTS "NetTotal" DECIMAL(18,4) DEFAULT 0;
ALTER TABLE "ImportShipments" ADD COLUMN IF NOT EXISTS "PaymentMode" VARCHAR(20);
ALTER TABLE "ImportShipments" ADD COLUMN IF NOT EXISTS "IsDemo" BOOLEAN DEFAULT FALSE;

-- IMPORT BAGS
ALTER TABLE "ImportBags" ADD COLUMN IF NOT EXISTS "IsDemo" BOOLEAN DEFAULT FALSE;

-- AWB TRACKINGS
ALTER TABLE "AWBTrackings" ADD COLUMN IF NOT EXISTS "ShipmentType" VARCHAR(50) DEFAULT 'Domestic';
ALTER TABLE "AWBTrackings" ADD COLUMN IF NOT EXISTS "MovementType" INT DEFAULT 0;
ALTER TABLE "AWBTrackings" ADD COLUMN IF NOT EXISTS "LocationId" BIGINT;
ALTER TABLE "AWBTrackings" ADD COLUMN IF NOT EXISTS "LocationName" VARCHAR(255);
ALTER TABLE "AWBTrackings" ADD COLUMN IF NOT EXISTS "EventCode" VARCHAR(50);
ALTER TABLE "AWBTrackings" ADD COLUMN IF NOT EXISTS "IsDemo" BOOLEAN DEFAULT FALSE;

-- AWB OTHER CHARGES
ALTER TABLE "AWBOtherCharges" ADD COLUMN IF NOT EXISTS "IsDemo" BOOLEAN DEFAULT FALSE;

-- PARTIES
ALTER TABLE "Parties" ADD COLUMN IF NOT EXISTS "AccountTypeId" BIGINT;
ALTER TABLE "Parties" ADD COLUMN IF NOT EXISTS "CreditLimit" DECIMAL(18,4) DEFAULT 0;
ALTER TABLE "Parties" ADD COLUMN IF NOT EXISTS "CreditPeriodDays" INT DEFAULT 0;
ALTER TABLE "Parties" ADD COLUMN IF NOT EXISTS "SLAAgreementId" BIGINT;
ALTER TABLE "Parties" ADD COLUMN IF NOT EXISTS "CustomerZoneId" BIGINT;
ALTER TABLE "Parties" ADD COLUMN IF NOT EXISTS "IsDemo" BOOLEAN DEFAULT FALSE;

-- INVOICES
ALTER TABLE "Invoices" ADD COLUMN IF NOT EXISTS "InvoiceFormat" VARCHAR(50) DEFAULT 'Commercial';
ALTER TABLE "Invoices" ADD COLUMN IF NOT EXISTS "GlJournalId" BIGINT;
ALTER TABLE "Invoices" ADD COLUMN IF NOT EXISTS "PostedAt" TIMESTAMP;
ALTER TABLE "Invoices" ADD COLUMN IF NOT EXISTS "PostedByUserId" BIGINT;
ALTER TABLE "Invoices" ADD COLUMN IF NOT EXISTS "PostedByUserName" VARCHAR(255);
ALTER TABLE "Invoices" ADD COLUMN IF NOT EXISTS "IsDemo" BOOLEAN DEFAULT FALSE;

-- INVOICE DETAILS
ALTER TABLE "InvoiceDetails" ADD COLUMN IF NOT EXISTS "FreightCost" DECIMAL(18,4) DEFAULT 0;
ALTER TABLE "InvoiceDetails" ADD COLUMN IF NOT EXISTS "TotalCost" DECIMAL(18,4) DEFAULT 0;
ALTER TABLE "InvoiceDetails" ADD COLUMN IF NOT EXISTS "ProfitAmount" DECIMAL(18,4) DEFAULT 0;
ALTER TABLE "InvoiceDetails" ADD COLUMN IF NOT EXISTS "ProfitPercentage" DECIMAL(10,4) DEFAULT 0;
ALTER TABLE "InvoiceDetails" ADD COLUMN IF NOT EXISTS "IsDemo" BOOLEAN DEFAULT FALSE;

-- RECEIPTS
ALTER TABLE "Receipts" ADD COLUMN IF NOT EXISTS "GlJournalId" BIGINT;
ALTER TABLE "Receipts" ADD COLUMN IF NOT EXISTS "IsDemo" BOOLEAN DEFAULT FALSE;

-- COD REMITTANCES
ALTER TABLE "CODRemittances" ADD COLUMN IF NOT EXISTS "GlJournalId" BIGINT;
ALTER TABLE "CODRemittances" ADD COLUMN IF NOT EXISTS "IsDemo" BOOLEAN DEFAULT FALSE;

-- JOURNALS
ALTER TABLE "Journals" ADD COLUMN IF NOT EXISTS "SourceType" VARCHAR(50);
ALTER TABLE "Journals" ADD COLUMN IF NOT EXISTS "SourceId" BIGINT;
ALTER TABLE "Journals" ADD COLUMN IF NOT EXISTS "SourceRefNo" VARCHAR(100);
ALTER TABLE "Journals" ADD COLUMN IF NOT EXISTS "IsDemo" BOOLEAN DEFAULT FALSE;

-- JOURNAL ENTRIES
ALTER TABLE "JournalEntries" ADD COLUMN IF NOT EXISTS "IsDemo" BOOLEAN DEFAULT FALSE;

-- RATE CARDS
ALTER TABLE "RateCards" ADD COLUMN IF NOT EXISTS "ServiceTypeId" BIGINT;
ALTER TABLE "RateCards" ADD COLUMN IF NOT EXISTS "ShipmentModeId" BIGINT;
ALTER TABLE "RateCards" ADD COLUMN IF NOT EXISTS "IsDemo" BOOLEAN DEFAULT FALSE;

-- RATE CARD ZONES
ALTER TABLE "RateCardZones" ADD COLUMN IF NOT EXISTS "ZoneCategoryId" BIGINT;
ALTER TABLE "RateCardZones" ADD COLUMN IF NOT EXISTS "BaseRateCost" DECIMAL(18,4) DEFAULT 0;
ALTER TABLE "RateCardZones" ADD COLUMN IF NOT EXISTS "IsDemo" BOOLEAN DEFAULT FALSE;

-- RATE CARD SLAB RULES
ALTER TABLE "RateCardSlabRules" ADD COLUMN IF NOT EXISTS "RateCost" DECIMAL(18,4) DEFAULT 0;
ALTER TABLE "RateCardSlabRules" ADD COLUMN IF NOT EXISTS "IsDemo" BOOLEAN DEFAULT FALSE;

-- SHIPMENT STATUSES
ALTER TABLE "ShipmentStatuses" ADD COLUMN IF NOT EXISTS "StatusGroupId" BIGINT;
ALTER TABLE "ShipmentStatuses" ADD COLUMN IF NOT EXISTS "IsDemo" BOOLEAN DEFAULT FALSE;

-- SHIPMENT STATUS GROUPS
ALTER TABLE "ShipmentStatusGroups" ADD COLUMN IF NOT EXISTS "SequenceNo" INT DEFAULT 0;
ALTER TABLE "ShipmentStatusGroups" ADD COLUMN IF NOT EXISTS "IconName" VARCHAR(100);
ALTER TABLE "ShipmentStatusGroups" ADD COLUMN IF NOT EXISTS "ColorCode" VARCHAR(20);
ALTER TABLE "ShipmentStatusGroups" ADD COLUMN IF NOT EXISTS "IsDemo" BOOLEAN DEFAULT FALSE;

-- GL CHART OF ACCOUNTS
ALTER TABLE "GLChartOfAccounts" ADD COLUMN IF NOT EXISTS "ClassificationId" BIGINT;
ALTER TABLE "GLChartOfAccounts" ADD COLUMN IF NOT EXISTS "IsDemo" BOOLEAN DEFAULT FALSE;

-- ZONE CATEGORIES
ALTER TABLE "ZoneCategories" ADD COLUMN IF NOT EXISTS "CategoryType" INT DEFAULT 0;
ALTER TABLE "ZoneCategories" ADD COLUMN IF NOT EXISTS "MovementType" INT DEFAULT 0;
ALTER TABLE "ZoneCategories" ADD COLUMN IF NOT EXISTS "ForwardingAgentId" BIGINT;
ALTER TABLE "ZoneCategories" ADD COLUMN IF NOT EXISTS "DeliveryAgentId" BIGINT;
ALTER TABLE "ZoneCategories" ADD COLUMN IF NOT EXISTS "SortOrder" INT DEFAULT 0;
ALTER TABLE "ZoneCategories" ADD COLUMN IF NOT EXISTS "CreatedByName" TEXT;
ALTER TABLE "ZoneCategories" ADD COLUMN IF NOT EXISTS "ModifiedByName" TEXT;
ALTER TABLE "ZoneCategories" ADD COLUMN IF NOT EXISTS "IsDemo" BOOLEAN DEFAULT FALSE;

-- FINANCIAL PERIODS
ALTER TABLE "FinancialPeriods" ADD COLUMN IF NOT EXISTS "IsDemo" BOOLEAN DEFAULT FALSE;

-- FINANCIAL YEARS
ALTER TABLE "FinancialYears" ADD COLUMN IF NOT EXISTS "OpeningBalanceJournalId" BIGINT;
ALTER TABLE "FinancialYears" ADD COLUMN IF NOT EXISTS "ClosingBalanceJournalId" BIGINT;
ALTER TABLE "FinancialYears" ADD COLUMN IF NOT EXISTS "IsDemo" BOOLEAN DEFAULT FALSE;

-- AUDIT LOGS
ALTER TABLE "AuditLogs" ADD COLUMN IF NOT EXISTS "IsDemo" BOOLEAN DEFAULT FALSE;

-- USERS
ALTER TABLE "Users" ADD COLUMN IF NOT EXISTS "LastLoginAt" TIMESTAMP;
ALTER TABLE "Users" ADD COLUMN IF NOT EXISTS "IsDemo" BOOLEAN DEFAULT FALSE;

-- ROLES
ALTER TABLE "Roles" ADD COLUMN IF NOT EXISTS "IsDemo" BOOLEAN DEFAULT FALSE;

-- SERVICE TYPES
ALTER TABLE "ServiceTypes" ADD COLUMN IF NOT EXISTS "IsDemo" BOOLEAN DEFAULT FALSE;

-- SHIPMENT MODES
ALTER TABLE "ShipmentModes" ADD COLUMN IF NOT EXISTS "IsDemo" BOOLEAN DEFAULT FALSE;

-- CURRENCIES
ALTER TABLE "Currencies" ADD COLUMN IF NOT EXISTS "IsDemo" BOOLEAN DEFAULT FALSE;

-- COUNTRIES
ALTER TABLE "Countries" ADD COLUMN IF NOT EXISTS "IsDemo" BOOLEAN DEFAULT FALSE;

-- STATES
ALTER TABLE "States" ADD COLUMN IF NOT EXISTS "IsDemo" BOOLEAN DEFAULT FALSE;

-- CITIES
ALTER TABLE "Cities" ADD COLUMN IF NOT EXISTS "IsDemo" BOOLEAN DEFAULT FALSE;

-- LOCATIONS
ALTER TABLE "Locations" ADD COLUMN IF NOT EXISTS "IsDemo" BOOLEAN DEFAULT FALSE;

-- PORTS
ALTER TABLE "Ports" ADD COLUMN IF NOT EXISTS "IsDemo" BOOLEAN DEFAULT FALSE;

-- VEHICLES
ALTER TABLE "Vehicles" ADD COLUMN IF NOT EXISTS "IsDemo" BOOLEAN DEFAULT FALSE;

-- WAREHOUSES
ALTER TABLE "Warehouses" ADD COLUMN IF NOT EXISTS "IsDemo" BOOLEAN DEFAULT FALSE;

-- MANIFESTS
ALTER TABLE "Manifests" ADD COLUMN IF NOT EXISTS "IsDemo" BOOLEAN DEFAULT FALSE;

-- DRS
ALTER TABLE "DRS" ADD COLUMN IF NOT EXISTS "IsDemo" BOOLEAN DEFAULT FALSE;

-- DRS DETAILS
ALTER TABLE "DRSDetails" ADD COLUMN IF NOT EXISTS "IsDemo" BOOLEAN DEFAULT FALSE;

-- PICKUP REQUESTS
ALTER TABLE "PickupRequests" ADD COLUMN IF NOT EXISTS "CustomerZoneId" BIGINT;
ALTER TABLE "PickupRequests" ADD COLUMN IF NOT EXISTS "IsDemo" BOOLEAN DEFAULT FALSE;

-- PREPAID AWBS
ALTER TABLE "PrepaidAWBs" ADD COLUMN IF NOT EXISTS "IsDemo" BOOLEAN DEFAULT FALSE;

-- AWB STOCKS
ALTER TABLE "AWBStocks" ADD COLUMN IF NOT EXISTS "IsDemo" BOOLEAN DEFAULT FALSE;

-- ACCOUNT TYPES
ALTER TABLE "AccountTypes" ADD COLUMN IF NOT EXISTS "IsDemo" BOOLEAN DEFAULT FALSE;

-- OTHER CHARGE TYPES
ALTER TABLE "OtherChargeTypes" ADD COLUMN IF NOT EXISTS "IsDemo" BOOLEAN DEFAULT FALSE;

-- TAX CODES
ALTER TABLE "TaxCodes" ADD COLUMN IF NOT EXISTS "IsDemo" BOOLEAN DEFAULT FALSE;

-- BANK ACCOUNTS
ALTER TABLE "BankAccounts" ADD COLUMN IF NOT EXISTS "IsDemo" BOOLEAN DEFAULT FALSE;

-- CASH BANK TRANSACTIONS
ALTER TABLE "CashBankTransactions" ADD COLUMN IF NOT EXISTS "IsDemo" BOOLEAN DEFAULT FALSE;

-- TICKETS
ALTER TABLE "Tickets" ADD COLUMN IF NOT EXISTS "IsDemo" BOOLEAN DEFAULT FALSE;

-- TICKET COMMENTS
ALTER TABLE "TicketComments" ADD COLUMN IF NOT EXISTS "IsDemo" BOOLEAN DEFAULT FALSE;

-- SLA AGREEMENTS
ALTER TABLE "SLAAgreements" ADD COLUMN IF NOT EXISTS "IsDemo" BOOLEAN DEFAULT FALSE;

-- EMPOST LICENSES
ALTER TABLE "EmpostLicenses" ADD COLUMN IF NOT EXISTS "IsDemo" BOOLEAN DEFAULT FALSE;

-- IMPORT SHIPMENT OTHER CHARGES
ALTER TABLE "ImportShipmentOtherCharge" ADD COLUMN IF NOT EXISTS "IsDemo" BOOLEAN DEFAULT FALSE;

-- IMPORT DOCUMENTS
ALTER TABLE "ImportDocuments" ADD COLUMN IF NOT EXISTS "IsDemo" BOOLEAN DEFAULT FALSE;

-- API SETTINGS
ALTER TABLE "ApiSettings" ADD COLUMN IF NOT EXISTS "IsDemo" BOOLEAN DEFAULT FALSE;

-- TRANSFER ORDERS
ALTER TABLE "TransferOrders" ADD COLUMN IF NOT EXISTS "IsDemo" BOOLEAN DEFAULT FALSE;

-- TRANSFER ORDER ITEMS
ALTER TABLE "TransferOrderItems" ADD COLUMN IF NOT EXISTS "IsDemo" BOOLEAN DEFAULT FALSE;

-- =============================================
-- END OF SCHEMA SYNC SCRIPT
-- =============================================
