-- Net4Courier Schema Sync - Simplified for Replit SQL Console
-- Only ALTER TABLE statements - run one section at a time if needed

-- BRANCHES
ALTER TABLE "Branches" ADD COLUMN IF NOT EXISTS "TimeZoneId" VARCHAR(100) DEFAULT 'Asia/Dubai';
ALTER TABLE "Branches" ADD COLUMN IF NOT EXISTS "UseAwbStockManagement" BOOLEAN DEFAULT FALSE;
ALTER TABLE "Branches" ADD COLUMN IF NOT EXISTS "HideAccountCodes" BOOLEAN DEFAULT FALSE;
ALTER TABLE "Branches" ADD COLUMN IF NOT EXISTS "VatPercentage" DECIMAL(5,2) DEFAULT 5.00;
ALTER TABLE "Branches" ADD COLUMN IF NOT EXISTS "IsDemo" BOOLEAN DEFAULT FALSE;

-- COMPANIES
ALTER TABLE "Companies" ADD COLUMN IF NOT EXISTS "UseAwbStockManagement" BOOLEAN DEFAULT FALSE;
ALTER TABLE "Companies" ADD COLUMN IF NOT EXISTS "InvoiceTermsAndConditions" TEXT;
ALTER TABLE "Companies" ADD COLUMN IF NOT EXISTS "BankAccountTitle" VARCHAR(255);
ALTER TABLE "Companies" ADD COLUMN IF NOT EXISTS "BankAccountTitleArabic" VARCHAR(255);
ALTER TABLE "Companies" ADD COLUMN IF NOT EXISTS "BankAccountNumber" VARCHAR(100);
ALTER TABLE "Companies" ADD COLUMN IF NOT EXISTS "BankIBANNumber" VARCHAR(100);
ALTER TABLE "Companies" ADD COLUMN IF NOT EXISTS "BankAccountType" VARCHAR(50);
ALTER TABLE "Companies" ADD COLUMN IF NOT EXISTS "BankAccountTypeArabic" VARCHAR(100);
ALTER TABLE "Companies" ADD COLUMN IF NOT EXISTS "BankCurrency" VARCHAR(20);
ALTER TABLE "Companies" ADD COLUMN IF NOT EXISTS "BankSWIFTCode" VARCHAR(50);
ALTER TABLE "Companies" ADD COLUMN IF NOT EXISTS "BankName" VARCHAR(255);
ALTER TABLE "Companies" ADD COLUMN IF NOT EXISTS "BankNameArabic" VARCHAR(255);
ALTER TABLE "Companies" ADD COLUMN IF NOT EXISTS "IsDemo" BOOLEAN DEFAULT FALSE;

-- IMPORT MASTERS
ALTER TABLE "ImportMasters" ADD COLUMN IF NOT EXISTS "InscannedAt" TIMESTAMP;
ALTER TABLE "ImportMasters" ADD COLUMN IF NOT EXISTS "InscannedByUserId" BIGINT;
ALTER TABLE "ImportMasters" ADD COLUMN IF NOT EXISTS "InscannedByUserName" VARCHAR(255);
ALTER TABLE "ImportMasters" ADD COLUMN IF NOT EXISTS "ClosedAt" TIMESTAMP;
ALTER TABLE "ImportMasters" ADD COLUMN IF NOT EXISTS "ClosedByUserId" BIGINT;
ALTER TABLE "ImportMasters" ADD COLUMN IF NOT EXISTS "ClosedByUserName" VARCHAR(255);
ALTER TABLE "ImportMasters" ADD COLUMN IF NOT EXISTS "CreatedByName" VARCHAR(255);
ALTER TABLE "ImportMasters" ADD COLUMN IF NOT EXISTS "ModifiedByName" VARCHAR(255);
ALTER TABLE "ImportMasters" ADD COLUMN IF NOT EXISTS "IsDemo" BOOLEAN DEFAULT FALSE;

-- IMPORT SHIPMENTS
ALTER TABLE "ImportShipments" ADD COLUMN IF NOT EXISTS "InscannedAt" TIMESTAMP;
ALTER TABLE "ImportShipments" ADD COLUMN IF NOT EXISTS "InscannedByUserId" BIGINT;
ALTER TABLE "ImportShipments" ADD COLUMN IF NOT EXISTS "InscannedByUserName" VARCHAR(255);
ALTER TABLE "ImportShipments" ADD COLUMN IF NOT EXISTS "CustomsValue" DECIMAL(18,4) DEFAULT 0;
ALTER TABLE "ImportShipments" ADD COLUMN IF NOT EXISTS "DutyAmount" DECIMAL(18,4) DEFAULT 0;
ALTER TABLE "ImportShipments" ADD COLUMN IF NOT EXISTS "DutyVatAmount" DECIMAL(18,4) DEFAULT 0;
ALTER TABLE "ImportShipments" ADD COLUMN IF NOT EXISTS "CalculatedImportVAT" DECIMAL(18,4) DEFAULT 0;
ALTER TABLE "ImportShipments" ADD COLUMN IF NOT EXISTS "NetTotal" DECIMAL(18,4) DEFAULT 0;
ALTER TABLE "ImportShipments" ADD COLUMN IF NOT EXISTS "PaymentMode" VARCHAR(20);
ALTER TABLE "ImportShipments" ADD COLUMN IF NOT EXISTS "IsDemo" BOOLEAN DEFAULT FALSE;

-- AWB TRACKINGS
ALTER TABLE "AWBTrackings" ADD COLUMN IF NOT EXISTS "ShipmentType" VARCHAR(50) DEFAULT 'Domestic';
ALTER TABLE "AWBTrackings" ADD COLUMN IF NOT EXISTS "MovementType" INT DEFAULT 0;
ALTER TABLE "AWBTrackings" ADD COLUMN IF NOT EXISTS "LocationId" BIGINT;
ALTER TABLE "AWBTrackings" ADD COLUMN IF NOT EXISTS "LocationName" VARCHAR(255);
ALTER TABLE "AWBTrackings" ADD COLUMN IF NOT EXISTS "EventCode" VARCHAR(50);
ALTER TABLE "AWBTrackings" ADD COLUMN IF NOT EXISTS "IsDemo" BOOLEAN DEFAULT FALSE;

-- PARTIES
ALTER TABLE "Parties" ADD COLUMN IF NOT EXISTS "AccountTypeId" BIGINT;
ALTER TABLE "Parties" ADD COLUMN IF NOT EXISTS "CreditLimit" DECIMAL(18,4) DEFAULT 0;
ALTER TABLE "Parties" ADD COLUMN IF NOT EXISTS "CreditPeriodDays" INT DEFAULT 0;
ALTER TABLE "Parties" ADD COLUMN IF NOT EXISTS "SLAAgreementId" BIGINT;
ALTER TABLE "Parties" ADD COLUMN IF NOT EXISTS "CustomerZoneId" BIGINT;
ALTER TABLE "Parties" ADD COLUMN IF NOT EXISTS "IsDemo" BOOLEAN DEFAULT FALSE;

-- INVOICES
ALTER TABLE "Invoices" ADD COLUMN IF NOT EXISTS "InvoiceFormat" VARCHAR(50) DEFAULT 'Commercial';
ALTER TABLE "Invoices" ADD COLUMN IF NOT EXISTS "GlJournalId" BIGINT;
ALTER TABLE "Invoices" ADD COLUMN IF NOT EXISTS "PostedAt" TIMESTAMP;
ALTER TABLE "Invoices" ADD COLUMN IF NOT EXISTS "PostedByUserId" BIGINT;
ALTER TABLE "Invoices" ADD COLUMN IF NOT EXISTS "PostedByUserName" VARCHAR(255);
ALTER TABLE "Invoices" ADD COLUMN IF NOT EXISTS "IsDemo" BOOLEAN DEFAULT FALSE;

-- INVOICE DETAILS
ALTER TABLE "InvoiceDetails" ADD COLUMN IF NOT EXISTS "FreightCost" DECIMAL(18,4) DEFAULT 0;
ALTER TABLE "InvoiceDetails" ADD COLUMN IF NOT EXISTS "TotalCost" DECIMAL(18,4) DEFAULT 0;
ALTER TABLE "InvoiceDetails" ADD COLUMN IF NOT EXISTS "ProfitAmount" DECIMAL(18,4) DEFAULT 0;
ALTER TABLE "InvoiceDetails" ADD COLUMN IF NOT EXISTS "ProfitPercentage" DECIMAL(10,4) DEFAULT 0;
ALTER TABLE "InvoiceDetails" ADD COLUMN IF NOT EXISTS "IsDemo" BOOLEAN DEFAULT FALSE;

-- RECEIPTS
ALTER TABLE "Receipts" ADD COLUMN IF NOT EXISTS "GlJournalId" BIGINT;
ALTER TABLE "Receipts" ADD COLUMN IF NOT EXISTS "IsDemo" BOOLEAN DEFAULT FALSE;

-- COD REMITTANCES
ALTER TABLE "CODRemittances" ADD COLUMN IF NOT EXISTS "GlJournalId" BIGINT;
ALTER TABLE "CODRemittances" ADD COLUMN IF NOT EXISTS "IsDemo" BOOLEAN DEFAULT FALSE;

-- JOURNALS
ALTER TABLE "Journals" ADD COLUMN IF NOT EXISTS "SourceType" VARCHAR(50);
ALTER TABLE "Journals" ADD COLUMN IF NOT EXISTS "SourceId" BIGINT;
ALTER TABLE "Journals" ADD COLUMN IF NOT EXISTS "SourceRefNo" VARCHAR(100);
ALTER TABLE "Journals" ADD COLUMN IF NOT EXISTS "IsDemo" BOOLEAN DEFAULT FALSE;

-- RATE CARDS
ALTER TABLE "RateCards" ADD COLUMN IF NOT EXISTS "ServiceTypeId" BIGINT;
ALTER TABLE "RateCards" ADD COLUMN IF NOT EXISTS "ShipmentModeId" BIGINT;
ALTER TABLE "RateCards" ADD COLUMN IF NOT EXISTS "IsDemo" BOOLEAN DEFAULT FALSE;

-- RATE CARD ZONES
ALTER TABLE "RateCardZones" ADD COLUMN IF NOT EXISTS "ZoneCategoryId" BIGINT;
ALTER TABLE "RateCardZones" ADD COLUMN IF NOT EXISTS "BaseRateCost" DECIMAL(18,4) DEFAULT 0;
ALTER TABLE "RateCardZones" ADD COLUMN IF NOT EXISTS "IsDemo" BOOLEAN DEFAULT FALSE;

-- RATE CARD SLAB RULES
ALTER TABLE "RateCardSlabRules" ADD COLUMN IF NOT EXISTS "RateCost" DECIMAL(18,4) DEFAULT 0;
ALTER TABLE "RateCardSlabRules" ADD COLUMN IF NOT EXISTS "IsDemo" BOOLEAN DEFAULT FALSE;

-- SHIPMENT STATUSES
ALTER TABLE "ShipmentStatuses" ADD COLUMN IF NOT EXISTS "StatusGroupId" BIGINT;
ALTER TABLE "ShipmentStatuses" ADD COLUMN IF NOT EXISTS "IsDemo" BOOLEAN DEFAULT FALSE;

-- SHIPMENT STATUS GROUPS
ALTER TABLE "ShipmentStatusGroups" ADD COLUMN IF NOT EXISTS "SequenceNo" INT DEFAULT 0;
ALTER TABLE "ShipmentStatusGroups" ADD COLUMN IF NOT EXISTS "IconName" VARCHAR(100);
ALTER TABLE "ShipmentStatusGroups" ADD COLUMN IF NOT EXISTS "ColorCode" VARCHAR(20);
ALTER TABLE "ShipmentStatusGroups" ADD COLUMN IF NOT EXISTS "IsDemo" BOOLEAN DEFAULT FALSE;

-- FINANCIAL YEARS
ALTER TABLE "FinancialYears" ADD COLUMN IF NOT EXISTS "OpeningBalanceJournalId" BIGINT;
ALTER TABLE "FinancialYears" ADD COLUMN IF NOT EXISTS "ClosingBalanceJournalId" BIGINT;
ALTER TABLE "FinancialYears" ADD COLUMN IF NOT EXISTS "IsDemo" BOOLEAN DEFAULT FALSE;

-- USERS
ALTER TABLE "Users" ADD COLUMN IF NOT EXISTS "LastLoginAt" TIMESTAMP;
ALTER TABLE "Users" ADD COLUMN IF NOT EXISTS "IsDemo" BOOLEAN DEFAULT FALSE;

-- PICKUP REQUESTS
ALTER TABLE "PickupRequests" ADD COLUMN IF NOT EXISTS "CustomerZoneId" BIGINT;
ALTER TABLE "PickupRequests" ADD COLUMN IF NOT EXISTS "IsDemo" BOOLEAN DEFAULT FALSE;

-- AWB OTHER CHARGES
ALTER TABLE "AWBOtherCharges" ADD COLUMN IF NOT EXISTS "IsDemo" BOOLEAN DEFAULT FALSE;

-- IMPORT BAGS
ALTER TABLE "ImportBags" ADD COLUMN IF NOT EXISTS "IsDemo" BOOLEAN DEFAULT FALSE;

-- GL CHART OF ACCOUNTS
ALTER TABLE "GLChartOfAccounts" ADD COLUMN IF NOT EXISTS "ClassificationId" BIGINT;
ALTER TABLE "GLChartOfAccounts" ADD COLUMN IF NOT EXISTS "IsDemo" BOOLEAN DEFAULT FALSE;
