namespace Net4Courier.Web.DTOs;

public record CashBankTransactionDto(
    Guid Id,
    Guid TenantId,
    DateTime CreatedAt,
    DateTime? UpdatedAt,
    string VoucherNo,
    DateTime VoucherDate,
    int TransactionType,
    string TransactionTypeText,
    int RecPayType,
    string RecPayTypeText,
    int TransactionCategory,
    string TransactionCategoryText,
    Guid SourceAccountId,
    string SourceAccountCode,
    string SourceAccountName,
    Guid? BankAccountId,
    string? BankAccountName,
    decimal TotalAmount,
    string? ChequeNo,
    DateTime? ChequeDate,
    bool IsPDC,
    string? BankName,
    string? BranchName,
    string? ReferenceNo,
    int Status,
    string StatusText,
    int ReceiptType,
    Guid? CustomerId,
    string? CustomerName,
    Guid? VendorId,
    string? VendorName,
    int DepositStatus,
    DateTime? ActualDepositDate,
    int ClearanceStatus,
    DateTime? ClearanceDate,
    string? BouncedReason,
    DateTime? PostedDate,
    Guid? PostedByUserId,
    bool IsVoided,
    DateTime? VoidedDate,
    Guid? VoidedByUserId,
    string? VoidReason,
    Guid? JournalEntryId,
    Guid? BranchId,
    string? OrganizationBranchName,
    Guid? DepartmentId,
    string? OrganizationDepartmentName,
    List<CashBankTransactionLineDto> Lines
);

public record CashBankTransactionLineDto(
    Guid Id,
    Guid TenantId,
    DateTime CreatedAt,
    Guid CashBankTransactionId,
    Guid DestinationAccountId,
    string DestinationAccountCode,
    string DestinationAccountName,
    decimal GrossAmount,
    decimal TaxRate,
    bool IsTaxInclusive,
    decimal NetAmount,
    decimal TaxAmount,
    Guid? ProjectId,
    string? ProjectName,
    int LineNumber,
    string Description
);

public record CreateCashBankTransactionRequest(
    string? VoucherNo,
    DateTime VoucherDate,
    int TransactionType,
    int RecPayType,
    int TransactionCategory,
    Guid SourceAccountId,
    Guid? BankAccountId,
    decimal TotalAmount,
    string? ChequeNo,
    DateTime? ChequeDate,
    bool IsPDC,
    string? BankName,
    string? BranchName,
    string? ReferenceNo,
    int ReceiptType,
    Guid? CustomerId,
    Guid? VendorId,
    Guid? BranchId,
    Guid? DepartmentId,
    List<CreateCashBankTransactionLineRequest> Lines
);

public record CreateCashBankTransactionLineRequest(
    Guid DestinationAccountId,
    decimal GrossAmount,
    decimal TaxRate,
    bool IsTaxInclusive,
    decimal NetAmount,
    decimal TaxAmount,
    Guid? ProjectId,
    int LineNumber,
    string Description
);

public record UpdateCashBankTransactionRequest(
    Guid Id,
    DateTime VoucherDate,
    int TransactionType,
    int RecPayType,
    int TransactionCategory,
    Guid SourceAccountId,
    Guid? BankAccountId,
    decimal TotalAmount,
    string? ChequeNo,
    DateTime? ChequeDate,
    bool IsPDC,
    string? BankName,
    string? BranchName,
    string? ReferenceNo,
    int ReceiptType,
    Guid? CustomerId,
    Guid? VendorId,
    Guid? BranchId,
    Guid? DepartmentId,
    List<CreateCashBankTransactionLineRequest> Lines
);

public record BankAccountDto(
    Guid Id,
    Guid TenantId,
    DateTime CreatedAt,
    DateTime? UpdatedAt,
    string AccountNumber,
    string AccountName,
    string BankName,
    string? BranchName,
    string? SwiftCode,
    string? IbanNumber,
    Guid ChartOfAccountId,
    string ChartOfAccountCode,
    string ChartOfAccountName,
    Guid? CurrencyId,
    string? CurrencyCode,
    string? CurrencyName,
    decimal OpeningBalance,
    DateTime? OpeningBalanceDate,
    string? Notes,
    bool IsActive,
    decimal CurrentBalance
);

public record CreateBankAccountRequest(
    string AccountNumber,
    string AccountName,
    string BankName,
    string? BranchName,
    string? SwiftCode,
    string? IbanNumber,
    Guid ChartOfAccountId,
    Guid? CurrencyId,
    decimal OpeningBalance,
    DateTime? OpeningBalanceDate,
    string? Notes,
    bool IsActive
);

public record UpdateBankAccountRequest(
    Guid Id,
    string AccountNumber,
    string AccountName,
    string BankName,
    string? BranchName,
    string? SwiftCode,
    string? IbanNumber,
    Guid ChartOfAccountId,
    Guid? CurrencyId,
    decimal OpeningBalance,
    DateTime? OpeningBalanceDate,
    string? Notes,
    bool IsActive
);
